- .github/workflows/jacoco-reports.yml
- api/acceptance-test/build.gradle
- api/acceptance-test/src/test/java/me/nalab/api/acceptancetest/jacoco/JacocoTest.java
- api/src/main/java/me.nalab.api/NalabApplication.java
- build.gradle
- settings.gradle
[우아한형제들 개발블로그 - Jacoco](https://techblog.woowahan.com/2661/)
> [Set up] : Jacoco task 생성

- .github/workflows/sonarcloud-analyze.yml
- README.md
- build.gradle
레포지토리에 sonarcloud를 연동했습니다.
Sonar cloud에 저희 프로젝트 현재 상태 (버그, 취약점, 코드 스맬) 등을 뱃지로 달아주는 서비스가 있어서, Readme.md에 추가했습니다.   
🚀 Readme.md 확인후에, 적용할 뱃지들을 확인해주시면 감사하겠습니다. 🚀   
Readme 상태입니다.   
[sonarcloud github action](https://github.com/SonarSource/sonarcloud-github-action)   
[sonarqube 공식문서](https://docs.sonarqube.org/latest/try-out-sonarqube/) sonarcloud가 설정 자동화가 잘 되어 있어서, 따로 공부할거는 없었고, sonarqube 공식문서(setup 부분)만 읽어도 적용가능했습니다.
> [Set up] Sonar cloud 연동

- core/data/build.gradle
- core/data/src/main/java/me/nalab/Main.java
- settings.gradle
- support/build.gradle
레포지토리 모듈에 필요한 모듈을 추가 했습니다.
[아키텍처 설명](https://www.notion.so/depromeet/207940cf46124f7ba2e58ef4d8a1eabd?pvs=4)
> [Set up] 아키텍처 모듈 추가

- build.gradle
lombok dependecy를 모든 모듈에 추가했습니다.
[lombok](https://projectlombok.org/setup/maven)
> [chore] : add lombok dependency

- .github/workflows/build-assure.yml
gradle build ci를 추가했습니다.
[Gradle Build Action - market place](https://github.com/marketplace/actions/gradle-build-action)
> [chore] : gradle build CI

- lombok.config
lombok을 jacoco test coverage측정에서 제외함
[lombok jacoco test coverage측정에서 제외하기](https://velog.io/@davidko/Jacoco-테스트-커버리지-excludes-안되는-문제)
> [chore] : `exclude lombok jacoco`

- core/data/build.gradle
- core/data/src/main/java/me/nalab/core/data/common/TimeBaseEntity.java
- core/data/src/main/java/me/nalab/core/data/common/TimeStamp.java
- core/data/src/main/java/me/nalab/core/data/survey/Choice.java
- core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestion.java
- core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestionType.java
- core/data/src/main/java/me/nalab/core/data/survey/FormQuestion.java
- core/data/src/main/java/me/nalab/core/data/survey/QuestionType.java
- core/data/src/main/java/me/nalab/core/data/survey/ShortFormQuestion.java
- core/data/src/main/java/me/nalab/core/data/survey/ShortFormQuestionType.java
- core/data/src/main/java/me/nalab/core/data/survey/Survey.java
- core/data/src/main/java/me/nalab/core/data/target/Target.java
- core/data/src/main/java/module-info.java
- coverage-exclude.luffy
Survey, Target @Entity 를 추가 했습니다.
> [feat] : `survey`, `target` @Entity 추가

- survey/application/src/main/java/me/nalab/survey/application/common/mapper/TargetDtoMapper.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/SurveyFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/TargetFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/survey/find/SurveyFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/target/find/TargetFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/survey/find/SurveyFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/target/find/TargetFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/service/survey/find/SurveyFindService.java
- survey/application/src/main/java/me/nalab/survey/application/service/target/find/TargetFindService.java
- survey/application/src/main/java/module-info.java
- survey/application/src/test/java/me/nalab/survey/application/common/mapper/TargetDtoMapperTest.java
- survey/application/src/test/java/me/nalab/survey/application/service/survey/find/SurveyFindServiceTest.java
- survey/application/src/test/java/me/nalab/survey/application/service/target/find/TargetFindServiceTest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/survey/find/SurveyFindController.java
질문 폼 조회 usecase의 application 모듈 쪽 구현 완료했습니다,
그리고 usecase의 구현체를 구현하였습니다
그리고 jpa-adaptor 모듈과 연결하기 전 port의 인터페이스까지 모두 구현이 완료되었습니다
이 다음에 바로 jaa-adaptor 모듈을 개발하면 될 것 같습니다
각 유즈케이스 별 역할이 잘 분담되어있고 이를 잘 구현했는지 확인해주시면 좋을 것 같고,
각 유즈케이스 구현체의 테스트부분도 확인해주시면 좋을 것 같습니다
> [feat] : 질문 폼 조회 usecase의 application 모듈 구현 완료

- .github/workflows/rebase-labeler.yml
- .github/workflows/squash-labeler.yml
squash merge가 필요한 상황과 rebase merge가 필요한 상황을 자동으로 라벨링 해주도록 수정
[Github action labele ecosystem](https://github.com/actions-ecosystem/action-add-labels)
> [feat] : `squash` `rebase` auto labeling

- .github/workflows/squash-labeler.yml
- .github/workflows/unit-analyze.yml
> [fix] : `base-branch` name strategy

- api/acceptance-test/build.gradle
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/AbstractDatabaseCleaner.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
- api/acceptance-test/src/test/resources/h2.properties
> [feat] : accept test `base template`

- core/exception-handler/src/test/java/me/nalab/core/exception/handler/TestRequest.java
- core/exception-handler/src/test/java/me/nalab/core/exception/handler/ValidationControllerAdviceTest.java
- survey/domain/src/main/java/me/nalab/survey/domain/exception/IllegalFeedbackException.java
- survey/domain/src/main/java/me/nalab/survey/domain/exception/IllegalQuestionFeedbackException.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/ChoiceFormQuestionFeedback.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/Feedback.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/Reviewer.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/ShortFormQuestionFeedback.java
- survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
- survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
- survey/domain/src/main/java/me/nalab/survey/domain/survey/ShortFormQuestion.java
- survey/domain/src/main/java/me/nalab/survey/domain/survey/Survey.java
- survey/domain/src/main/java/me/nalab/survey/domain/survey/spi/FeedbackValidable.java
- survey/domain/src/main/java/me/nalab/survey/domain/survey/spi/QuestionFeedbackValidable.java
- survey/domain/src/main/java/module-info.java
- survey/domain/src/test/java/me/nalab/survey/domain/RandomSurveyFixture.java
- survey/domain/src/test/java/me/nalab/survey/domain/feedback/FeedbackDomainTest.java
feedback 도메인과 관련 정책, 테스트 코드를 개발했습니다.
> [feat] : feedback 도메인과 정책 로직 추가

- core/data/src/main/java/me/nalab/core/data/feedback/ChoiceFormFeedbackEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/FeedbackEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/FeedbackEntityType.java
- core/data/src/main/java/me/nalab/core/data/feedback/FormFeedbackEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/ReplyEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/ReviewerEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/SelectEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/ShortFormFeedbackEntity.java
- core/exception-handler/src/test/java/me/nalab/core/exception/handler/TestRequest.java
- core/exception-handler/src/test/java/me/nalab/core/exception/handler/ValidationControllerAdviceTest.java
- coverage-exclude.luffy
> [feat] : feedback 도메인 설계

- core/data/src/main/java/me/nalab/core/data/feedback/ChoiceFormFeedbackEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/FeedbackEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/FeedbackEntityType.java
- core/data/src/main/java/me/nalab/core/data/feedback/FormFeedbackEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/ReplyEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/ReviewerEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/SelectEntity.java
- core/data/src/main/java/me/nalab/core/data/feedback/ShortFormFeedbackEntity.java
- core/exception-handler/src/test/java/me/nalab/core/exception/handler/TestRequest.java
- core/exception-handler/src/test/java/me/nalab/core/exception/handler/ValidationControllerAdviceTest.java
- coverage-exclude.luffy
feedback 도메인 개발을 완료했습니다
연관관계 매핑이 위주로 확인 부탁드립니다
네이밍도 같이 봐주시면 좋을 것 같습니다
> [feat] : feedback 도메인 설계 (#79)

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
feedback 인수테스트 `테스트 격리 자동화` 시켰고, feedback 인수테스트 기본 템플릿을 만들었습니다.
인수테스트 작성시, `// :TODO` 참고해서 작성하시고 나중에 `// :TODO`는 지워주세요
> [test] : feedback `인수테스트 supporter` 추가

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/find/SurveyFindAcceptanceTest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/survey/find/SurveyFindController.java
> [feat] : 질문 폼 조회 인수테스트 작성

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/FeedbackCreateAcceptanceTest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/request/AbstractQuestionFeedbackRequest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/request/ChoiceQuestionFeedbackRequest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/request/FeedbackCreateRequest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/request/ReviewerRequest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/request/ShortQuestionFeedbackRequest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/ChoiceFormQuestionResponse.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/ChoiceResponse.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/FormQuestionResponseable.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/ShortFormQuestionResponse.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/SurveyFindResponse.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/TargetResponse.java
> [test] : `feedback 생성` 인수테스트 작성

- coverage-exclude.luffy
- survey/application/src/main/java/module-info.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/FeedbackCreateController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/AbstractQuestionFeedbackRequest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/ChoiceQuestionFeedbackRequest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/FeedbackCreateRequest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/ReviewerRequest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/ShortQuestionFeedbackRequest.java
`Feedback web-adaptor` 를 구현했습니다.
> [feat] : `Feedback web-adaptor` 생성

- survey/application/src/main/java/me/nalab/survey/application/common/feedback/mapper/FeedbackDtoMapper.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/summaryreviewer/ReviewerSummarizeUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/summaryreviewer/ReviewerFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/summaryreviewer/SurveyExistCheckPort.java
- survey/application/src/main/java/me/nalab/survey/application/service/summaryreviewer/ReviewerSummaryGetService.java
- survey/application/src/main/java/module-info.java
- survey/application/src/test/java/me/nalab/survey/application/TestIdGenerator.java
- survey/application/src/test/java/me/nalab/survey/application/service/summaryreviewer/ReviewerSummaryGetServiceTest.java
`reviewer summary` 유즈케이스를 생성했습니다.
> [feat] : `reviewer summary` usecase 생성

- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/summaryreviewer/ReviewerFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/summaryreviewer/SurveyExistCheckPort.java
- survey/application/src/main/java/module-info.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/ReviewerEntityMapper.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/ReviewerFindAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/SurveyExistCheckAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/repository/ReviewerFindJpaRepository.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/repository/SurveyExistCheckJpaRepository.java
- survey/jpa-adaptor/src/main/java/module-info.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/ReviewerFindAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/SurveyExistCheckAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/TestFeedbackJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/TestSurveyJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/TestTargetJpaRepository.java
리뷰어 요약 유즈케이스의 `jpa adaptor`를 추가했습니다.
> [feat] : reviewer summary `jpa adaptor` 추가

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/reviewer/summary/ReviewerSummarizeAcceptanceTest.java
- survey/application/src/main/java/me/nalab/survey/application/common/feedback/mapper/FeedbackDtoMapper.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/ReveiwerSummaryController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/CollaborationSummaryResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/PositionSummaryReponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/ReviewerSummaryResponse.java
`summary reviewer` 기능의 인수테스트가 돌아가지 않는 버그를 수정했습니다.
> [fix] : `summary reviewer` 인수테스트 돌아가지 않는 버그 수정

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/reviewer/summary/ReviewerSummarizeAcceptanceTest.java
- coverage-exclude.luffy
- survey/application/src/main/java/me/nalab/survey/application/common/feedback/mapper/FeedbackDtoMapper.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/summaryreviewer/ReviewerSummarizeUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/summaryreviewer/ReviewerFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/summaryreviewer/SurveyExistCheckPort.java
- survey/application/src/main/java/me/nalab/survey/application/service/summaryreviewer/ReviewerSummaryGetService.java
- survey/application/src/main/java/module-info.java
- survey/application/src/test/java/me/nalab/survey/application/TestIdGenerator.java
- survey/application/src/test/java/me/nalab/survey/application/service/summaryreviewer/ReviewerSummaryGetServiceTest.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/ReviewerEntityMapper.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/ReviewerFindAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/SurveyExistCheckAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/repository/ReviewerFindJpaRepository.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/summaryreviewer/repository/SurveyExistCheckJpaRepository.java
- survey/jpa-adaptor/src/main/java/module-info.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/ReviewerFindAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/SurveyExistCheckAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/TestFeedbackJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/TestSurveyJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/summaryreviewer/TestTargetJpaRepository.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/ReveiwerSummaryController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/ReviewerSummaryResponseMapper.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/CollaborationSummaryResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/PositionSummaryReponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/ReviewerSummaryResponse.java
> [feat] : `reviewer summary` 기능 개발 완료

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackCreateRequestFixture.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindAcceptanceTest.java
> [test] : feedback 조회 `인수테스트 작성`

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findreviewers/ReviewersFindAcceptanceTest.java
- coverage-exclude.luffy
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/feedbackreviewers/FeedbackReviewersFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbackreviewers/FeedbacksFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/service/feedbackreviewers/FeedbackReviewersFindService.java
- survey/application/src/main/java/module-info.java
- survey/application/src/test/java/me/nalab/survey/application/service/feedbackreviewers/FeedbackReviewersFindServiceTest.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/repository/FeedbackFindJpaRepository.java
- survey/jpa-adaptor/src/main/java/module-info.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/TestFeedbackFindJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/TestSurveyCreateJpaRepository.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersResponseMapper.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/FeedbackReviewer.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/FeedbackReviewersResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/ReviewerResponse.java
- survey/web-adaptor/src/test/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersResponseMapperTest.java
질문 폼의 모든 피드백-리뷰어 목록 조회 기능 개발을 완료했습니다
> [feat] : `질문 폼의 모든 피드백-리뷰어 목록 조회` 기능 개발 완료

- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/ReveiwerSummaryController.java
ReviewerSummaryController에서, code smell을 제거했습니다.
> [refactor] : ReviewerSummaryController `code smell 제거`

- core/id-generator/id-generator-starter/build.gradle
- core/id-generator/id-generator-starter/src/main/java/me/nalab/core/idgenerator/starter/IdGeneratorConfigurer.java
- core/id-generator/id-generator-starter/src/main/java/module-info.java
- core/id-generator/tsid/build.gradle
- core/id-generator/tsid/src/main/java/me/nalab/core/idgenerator/tsid/TsidGenerator.java
- core/id-generator/tsid/src/main/java/me/nalab/core/idgenerator/tsid/engine/TsidEngine.java
- core/id-generator/tsid/src/main/java/module-info.java
- core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/DefaultTsidActor.java
- core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/ThreadTsidActor.java
- core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/TsidConfigurer.java
- core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/TsidPerformanceTest.java
- coverage-exclude.luffy
- settings.gradle
Tsid generator 개발 완료 했습니다. 
이전의 리뷰받은거 main으로 합치는 동작이라..! 별도의 리뷰는 없어도 될거같습니다!
> [feat] : TSID id generator 개발 완료

- settings.gradle
- user/.gitignore
- user/domain/.gitignore
- user/domain/src/main/java/me/nalab/user/domain/user/Provider.java
- user/domain/src/main/java/me/nalab/user/domain/user/User.java
> [domain] User 도메인 정의

- api/acceptance-test/build.gradle
- api/build.gradle
- api/src/main/java/me/nalab/api/NalabApplication.java
- api/src/main/resources/application.properties
API 모듈에서 다른 기능, 라이브러리 모듈로의 의존성을 추가했습니다.
> [chore] : api 에서 다른모듈로 의존성 추가

- Dockerfile
정말 필요한것만 있는 docker 파일을 생성했습니다.
> [feat] : simple docker 생성

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findspecific/SpecificFindAcceptanceTest.java
- coverage-exclude.luffy
- survey/application/src/main/java/me/nalab/survey/application/exception/FeedbackDoesNotExistException.java
- survey/application/src/main/java/me/nalab/survey/application/exception/SurveyDoesNotHasTargetException.java
- survey/application/src/main/java/me/nalab/survey/application/port/in/web/findspecific/SpecificFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findspecific/FeedbackFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findspecific/SurveyFindPort.java
- survey/application/src/main/java/me/nalab/survey/application/service/findspecific/SpecificFindService.java
- survey/application/src/main/java/module-info.java
- survey/application/src/test/java/me/nalab/survey/application/service/findspecific/SpecificFindServiceTest.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackFindAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/SurveyFindAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/repository/FeedbackFindJpaRepository.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/repository/SurveyFindJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackFindAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/SurveyFindAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/TestFeedbackFindJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/TestSurveyFindJpaRepository.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/SpecificFeedbackController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/SpecificFeedbackResponseMapper.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/response/ChoiceFormFeedbackResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/response/ChoiceResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/response/FormFeedbackResponseable.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/response/ReviewerResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/response/ShortFormFeedbackResponse.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/response/SpecificFeedbackResponse.java
> [feat] : `개별 피드백 응답 조회` 기능 개발 완료

- coverage-exclude.luffy
- survey/web-adaptor/src/test/java/me/nalab/survey/web/adaptor/findspecific/SpecificFeedbackResponseMapperTest.java
개별 피드백 응답 조회 mapper에 대한 테스트를 추가하였습니다
> [test] : SpecificFeedbackResponseMapper test 추가

- auth/auth-application/.gitignore
- auth/auth-application/build.gradle
- auth/auth-application/src/main/java/me/nalab/auth/application/common/config/PropertyConfig.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/AuthToken.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/CreateAuthTokenRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/Payload.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/property/JwtProperties.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/utils/JwtUtils.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/in/web/AuthTokenCreateUseCase.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/AuthTokenCreateService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/JwtService.java
- auth/auth-application/src/main/java/module-info.java
- auth/auth-application/src/main/resources/application.yml
- auth/auth-application/src/test/java/me/nalab/auth/application/service/AuthTokenCreateServiceTest.java
- coverage-exclude.luffy
- settings.gradle
- AuthToken 생성 로직 및 jwt utils 추가
- AuthToken 생성 로직 테스트
- [jwt library](https://github.com/auth0/java-jwt#getting-started)
> [feat] AuthToken 생성 로직 추가

- api/build.gradle
- core/secure/build.gradle
- core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java
- core/secure/src/main/java/module-info.java
- settings.gradle
> [feat] : CORS 핸들러 추가

- .github/workflows/docker-publisher.yml
- .github/workflows/release-labeler.yml
- .github/workflows/start-api-server.yml
- api/build.gradle
- core/secure/build.gradle
- core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java
- core/secure/src/main/java/module-info.java
- settings.gradle
CORS 핸들링이 추가된 버전 release 입니다.
이 PR에 포함된 PR들
> [feat] : CORS 핸들링 버전 release

- api/api-mock/build.gradle
- api/api-mock/src/main/java/me/nalab/api/mock/MockController.java
- api/build.gradle
- core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java
- coverage-exclude.luffy
- settings.gradle
`mocking api` 를 추가했습니다.
일단은, Notion api문서에 정의된 값 그대로 내려주게끔 만들었고.. 빠르게 드려야 할거 같아서 그대로 복사해서 가져왔어요
개발 완료되고 삭제하면 될거 같습니다.
> [chore] : `mocking api` 추가

- api/api-mock/src/main/java/me/nalab/api/mock/MockController.java
- core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java
- core/secure/src/main/java/module-info.java
mock api에서 `/v1` 이 들어가 있는 버그를 수정하고, cors 에러를 수정했습니다.
> [fix] : mock api 수정

- core/data/src/main/java/me/nalab/core/data/user/UserOAuthInfoEntity.java
- user/domain/src/main/java/me/nalab/user/domain/user/Provider.java
- user/domain/src/main/java/me/nalab/user/domain/user/User.java
- user/domain/src/main/java/me/nalab/user/domain/user/UserOAuthInfo.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/common/mapper/UserOAuthInfoMapper.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/common/mapper/UserObjectMapper.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/common/mapper/UserObjectMapperTest.java
- OAuth 관련 정보를 저장하는 UserOAuthInfo를 정의
- OAuth 객체 정의에 따른 User 객체 수정
> [domain] UserOAuthInfo 정의

- user/application/src/test/java/me/nalab/user/application/service/UserFindByProviderAndTokenServiceTest.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/UserFindByProviderAndTokenAdaptor.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/common/mapper/UserOAuthInfoMapper.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/repository/UserJpaRepository.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/repository/UserOAuthInfoJpaRepository.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/UserCreateAdaptorTest.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/UserFindByProviderAndTokenAdaptorTest.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/UserOAuthInfoTestUtils.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/UserTestUtils.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/common/mapper/UserOAuthInfoMapperTest.java
- user/jpa-adapter/src/test/resources/application-test.yaml
- User 수정에 따른 테스트 코드 수정
- UserOAuthInfo 추가에 따른 테스트 코드 추가
> [Test] Domain 변경에 따른 테스트 수정 및 추가

- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/SignUpWithOAuthRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/in/web/SignUpWithOAuthUseCase.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignUpWithOAuthService.java
- auth/auth-application/src/main/java/module-info.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/SignUpWithOAuthServiceTest.java
- user/application/build.gradle
- user/application/src/main/java/me/nalab/user/application/common/dto/CreateUserWithOAuthRequest.java
- user/application/src/main/java/me/nalab/user/application/port/in/UserCreateWithOAuthUseCase.java
- user/application/src/main/java/me/nalab/user/application/port/out/persistence/UserCreateWithOAuthPort.java
- user/application/src/main/java/me/nalab/user/application/service/UserCreateWithOAuthService.java
- user/application/src/main/java/module-info.java
- user/application/src/test/java/me/nalab/user/application/service/UserCreateWithOAuthServiceTest.java
- user/domain/src/main/java/me/nalab/user/domain/user/Provider.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/UserCreateWithOAuthAdaptor.java
- user/jpa-adapter/src/test/java/me/nalab/user/jpa/adaptor/create/UserCreateWithOAuthAdaptorTest.java
- OAuth를 이용한 유저 생성 기능 구현
- OAuth를 이용한 유저 생성 기능 테스트 구현
> [Feat] OAuth를 이용한 유저 생성 구현

- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/SignUpWithOAuthRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/AuthTokenCreateService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignUpWithOAuthService.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/AuthTokenCreateServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/SignUpWithOAuthServiceTest.java
- input 값에 대한 null / empty 체크 로직을 수정 반영
- dto 빌더 추가 및 테스트 코드 dto 생성 함수 처리
> [FIX] String Null and Empty 검증 수정 / dto 빌더 추가

- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/SignInWithOAuthRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/in/web/SignInWithOAuthUseCase.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/in/web/SignUpWithOAuthUseCase.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignInWithOAuthService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignUpWithOAuthService.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/SignInWithOAuthServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/SignUpWithOAuthServiceTest.java
- user/application/src/main/java/me/nalab/user/application/port/in/UserCreateWithOAuthUseCase.java
- user/application/src/main/java/me/nalab/user/application/port/out/persistence/UserCreateWithOAuthPort.java
- user/application/src/main/java/me/nalab/user/application/service/UserCreateWithOAuthService.java
- user/application/src/test/java/me/nalab/user/application/service/UserCreateWithOAuthServiceTest.java
- user/jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/UserCreateWithOAuthAdaptor.java
- OAuth를 이용한 로그인 기능 구현
- OAuth를 이용한 로그인 기능 테스트 구현
> [Feat] OAuth를 이용한 로그인 구현

- .github/workflows/type-labeler.yml
> [chore] : issues auto labelling

- user/user-application/src/main/java/me/nalab/user/application/common/dto/LoginedInfo.java
- user/user-application/src/main/java/me/nalab/user/application/port/in/LoginedUserGetByTokenUseCase.java
- user/user-application/src/main/java/me/nalab/user/application/port/out/persistence/LoginedUserGetByTokenPort.java
- user/user-application/src/main/java/me/nalab/user/application/service/LoginedUserGetByTokenService.java
- user/user-application/src/test/java/me/nalab/user/application/service/LoginedUserGetByTokenServiceTest.java
> [feat] : logined user 정보 조회 `유즈케이스 추가`

- api/acceptance-test/build.gradle
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/logined/LoginedTargetFindAcceptanceTest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/Payload.java
- user/user-domain/src/main/java/me/nalab/user/domain/user/Provider.java
로그인된 유저를 조회하는 인수테스트를 작성했습니다.
근데 슬랙에 올라와있는 property 이슈로 막혀있어요 ㅠㅠ 도진님 수정 pr 올라오면 나중에 merge하고 올리겠습니다
> [test] : login 된 유저 조회 인수테스트 작성

- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/advice/FeedbackControllerAdvice.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/advice/SurveyControllerAdvice.java
에러 핸들링 누락된 부분을 추가했습니다.
일단, survey에서 Exception은 있는데 잡는 부분이 없는곳만 잡아주긴 했는데, 나중 리팩토링때 함 더 체크해야할듯 해용
> [fix] : 에러핸들링 누락된 부분 추가

- api/acceptance-test/build.gradle
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/UserInitializer.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/AbstractAuthTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/SignInWithOAuthAcceptanceTest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignInWithOAuthService.java
- auth/auth-application/src/main/java/module-info.java
- auth/auth-web-adaptor/.gitignore
- auth/auth-web-adaptor/build.gradle
- auth/auth-web-adaptor/src/main/java/me/nalab/auth/web/adaptor/api/SignInWithOAuthController.java
- auth/auth-web-adaptor/src/main/java/module-info.java
- settings.gradle
- user/user-application/src/main/java/me/nalab/user/application/service/UserFindByProviderAndTokenService.java
- OAuth 기반 로그인 api 구현
- OAuth 기반 로그인 api 인수 테스트 작성
> [API] OAuth 기반 로그인 api 구현 및 인수 테스트 작성

- auth/auth-application/build.gradle
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/CreateAuthTokenRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/AuthTokenCreateService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignInWithOAuthService.java
- auth/auth-application/src/main/java/module-info.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/AuthTokenCreateServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/SignInWithOAuthServiceTest.java
- token payload에 target Id를 추가
> [FIX] token payload에 targetId 추가

- api/build.gradle
- auth/auth-application/build.gradle
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/CreateAuthTokenRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/in/web/TargetIdGetPort.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/AuthTokenCreateService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/JwtLoginedDecryptService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/SignInWithOAuthService.java
- auth/auth-application/src/main/java/module-info.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/AuthTokenCreateServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/JwtLoginedDecryptServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/SignInWithOAuthServiceTest.java
- auth/auth-interceptor/build.gradle
- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/CannotValidMockTokenException.java
- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java
- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
- auth/auth-interceptor/src/main/java/module-info.java
- auth/auth-web-adaptor/src/main/java/module-info.java
- coverage-exclude.luffy
- settings.gradle
인증관련 기능 
- 유저 토큰 복호화
- 인터셉터
- 회원가입 및 로그인
기능을 추가했습니다.
> [feat] : 인증 관련 기능 추가

- api/src/main/resources/db/migration/V2__add_user.sql
user 엔티티와 user_oath_info 엔티티에 대한 DDL을 v2로 추가했습니다
> [chore] : DDL에 user와 user_oauth_info 추가

- api/src/main/resources/db/migration/V2__add_user.sql
> [fix] : flyway v2 ddl 수정

- api/build.gradle
> [chore] : mock api 다시 추가

- core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java
> [fix] : CORS 구체 경로 추가

- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java
- core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java
JwtInterceptor가 Preflight 요청에서도 호출되는 버그를 수정했습니다.
> [fix] : JwtInterceptor cors config 수정 릴리즈

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/AbstractAuthTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/SignInWithOAuthAcceptanceTest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/AccessToken.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/OAuthResourceRequest.java
- auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/OAuthResourceResponse.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/in/web/OAuthGetResourceUseCase.java
- auth/auth-application/src/main/java/me/nalab/auth/application/port/out/OAuthWebClientPort.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/OAuthGetAccessTokenService.java
- auth/auth-application/src/main/java/me/nalab/auth/application/service/OAuthGetResourceService.java
- auth/auth-application/src/test/java/me/nalab/auth/application/WebClientFactory.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/AuthorizeWithOauthServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/OAuthGetAccessTokenServiceTest.java
- auth/auth-application/src/test/java/me/nalab/auth/application/service/OAuthGetResourceServiceTest.java
- auth/auth-web-adaptor/src/main/java/me/nalab/auth/web/adaptor/api/SignInWithOAuthController.java
- auth/auth-web-adaptor/src/main/java/me/nalab/auth/web/adaptor/exception/UserOAuthRejectException.java
- auth/oauth-application/src/main/java/me/nalab/oauth/application/exception/OAuthResourceNotResponseException.java
- auth/oauth-application/src/main/java/me/nalab/oauth/application/kakao/KakaoClientProperties.java
- auth/oauth-application/src/main/java/me/nalab/oauth/application/kakao/KakaoOAuthWebClient.java
- auth/oauth-application/src/main/java/me/nalab/oauth/application/kakao/dto/KakaoAccount.java
- auth/oauth-application/src/main/java/me/nalab/oauth/application/kakao/dto/ResourceResponse.java
- auth/oauth-application/src/main/java/module-info.java
- coverage-exclude.luffy
- 사용자 로그인 이후 리다이렉트되는 서버 내부 로직 구현
- 엑세스 토큰 발급
- 리소스 서버에서 사용자 데이터 조회
- 리소스 서버를 이용한 로그인 처리
> [feat] kakao redirect 후 리소스 서버 접근 로직 처리

- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/ResponseMapper.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/response/feedback/ShortFeedbackResponse.java
feedback.short 응답에서 누락된 필드를 추가했습니다.
> [fix] : `feedback.short` 누락된 필드 추가

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/AbstractAuthTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/SignInWithOAuthV1AcceptanceTest.java
- auth/auth-web-adaptor/src/main/java/me/nalab/auth/web/adaptor/api/SignInWithOAuthController.java
- auth/auth-web-adaptor/src/main/java/me/nalab/auth/web/adaptor/api/SignInWithOAuthV1Controller.java
- 기존 로그인 방식을 위한 V1 controller를 살렸습니다
> [fix] 기존 로그인 방식을 위한 v1 api 재생성

- coverage-exclude.luffy
- auth controller 패키지 exclude 했습니다
> [chore] controller exclude 추가

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/SignInWithOAuthV1AcceptanceTest.java
- 유저 로그인 시 조회하는 target 초기화를 해줍니다.
> [fix] target 초기화 추가

- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/authorization/TargetIdFindPort.java
- survey/application/src/main/java/module-info.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/authorization/repository/TargetIdFindJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TestFeedbackJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TestSurveyJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TestTargetJpaRepository.java
survey 권한 서비스의 Jpa-apdator 모듈을 구현했습니다.
> [feat] : survey authorization jpa-adaptor 모듈 구현

- .github/workflows/docker-publisher.yml
- Dockerfile
- api/build.gradle
- api/src/main/resources/application.properties
- api/src/main/resources/logback-spring.xml
- core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/advice/AuthorizationExceptionAdvice.java
- core/exception-handler/src/main/java/me/nalab/core/exception/handler/ValidationControllerAdvice.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/advice/FeedbackControllerAdvice.java
- sentry 및 logback 설정 추가
fix #248
> [Chore] logback, sentry 설정 추가

- core/secure/build.gradle
- core/secure/src/main/java/me/nalab/core/secure/cors/CorsConfig.java
- core/secure/src/main/java/me/nalab/core/secure/xss/config/XssConfig.java
- core/secure/src/main/java/me/nalab/core/secure/xss/engine/XssEngine.java
- core/secure/src/main/java/me/nalab/core/secure/xss/engine/aop/XssAopEngine.java
- core/secure/src/main/java/me/nalab/core/secure/xss/exception/UnknownXssFilterException.java
- core/secure/src/main/java/me/nalab/core/secure/xss/exception/UnknownXssFilterName.java
- core/secure/src/main/java/me/nalab/core/secure/xss/meta/Xss.java
- core/secure/src/main/java/me/nalab/core/secure/xss/meta/XssFiltering.java
- core/secure/src/main/java/me/nalab/core/secure/xss/spi/XssFilter.java
- core/secure/src/test/java/me/nalab/core/secure/xss/XssFilterAopRegisterTest.java
- core/secure/src/test/java/me/nalab/core/secure/xss/XssFilterTarget.java
- core/secure/src/test/java/me/nalab/core/secure/xss/XssTestFilter.java
- coverage-exclude.luffy
xss filter 인터페이스를 정의했습니다.
fix #247
> [feat] : xss interface 및 engine 정의

- core/secure/build.gradle
- core/secure/src/main/java/me/nalab/core/secure/xss/json/JsonXssFilter.java
- core/secure/src/main/java/me/nalab/core/secure/xss/json/JsonXssFilterException.java
- core/secure/src/main/java/me/nalab/core/secure/xss/json/XssCharacterEscapes.java
- core/secure/src/test/java/me/nalab/core/secure/xss/json/JsonXssFilterTest.java
- core/secure/src/test/java/me/nalab/core/secure/xss/json/Request.java
- core/secure/src/test/java/me/nalab/core/secure/xss/json/RequestWrapper.java
- coverage-exclude.luffy
JSON 요청을 filtering 해주는 Json Xss Filter를 추가했습니다.
https://jojoldu.tistory.com/470
> [feat] : JSON xss filter 추가

- survey/application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/FeedbackFindUseCase.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/FeedbackUpdatePort.java
- survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findspecific/FeedbackUpdatePort.java
- survey/application/src/main/java/me/nalab/survey/application/service/findfeedback/FeedbackFindService.java
- survey/application/src/main/java/me/nalab/survey/application/service/findspecific/SpecificFindService.java
- survey/application/src/test/java/me/nalab/survey/application/service/findfeedback/FeedbackFindServiceTest.java
- survey/application/src/test/java/me/nalab/survey/application/service/findspecific/SpecificFindServiceTest.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/Feedback.java
- survey/domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/FeedbackUpdateAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/repository/FeedbackUpdateRepository.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackUpdateAdaptor.java
- survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/repository/FeedbackUpdateJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/FeedbackUpdateAdaptorTest.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/TestFeedbackUpdateJpaRepository.java
- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackUpdateAdaptorTest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/FeedbackFindController.java
* [리뷰어 개별 응답 목록]에서의 `읽음 처리 기능` 로직을 변경하고
* [피드백 일지]에서 `읽음 처리 기능` 을 추가하였습니다
그리고 각각에 대한 테스트코드를 모두 작성하였습니다
- #246
> [feat] : `읽음 처리 기능` 수정 및 추가

- survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/FeedbackUpdateAdaptorTest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/SurveyCreateRequest.java
질문 폼 생성 request에서 validation을 수정하였습니다
> [fix] : 질문 폼 생성 validation 수정

- core/secure/src/main/java/module-info.java
- survey/web-adaptor/build.gradle
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/FeedbackCreateController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/SurveyCreateController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/ChoiceFormQuestionRequest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/ShortFormQuestionRequest.java
- survey/web-adaptor/src/main/java/module-info.java
생성 Controller에 `@XssFiltering`을 부착했습니다.
> [feat] : 생성에 `@XssFiltering` 부착

- core/secure/build.gradle
- core/secure/src/main/java/me/nalab/core/secure/cors/CorsConfig.java
- core/secure/src/main/java/me/nalab/core/secure/xss/config/XssConfig.java
- core/secure/src/main/java/me/nalab/core/secure/xss/engine/XssEngine.java
- core/secure/src/main/java/me/nalab/core/secure/xss/engine/aop/XssAopEngine.java
- core/secure/src/main/java/me/nalab/core/secure/xss/exception/UnknownXssFilterException.java
- core/secure/src/main/java/me/nalab/core/secure/xss/json/JsonXssFilter.java
- core/secure/src/main/java/me/nalab/core/secure/xss/json/JsonXssFilterException.java
- core/secure/src/main/java/me/nalab/core/secure/xss/json/XssCharacterEscapes.java
- core/secure/src/main/java/me/nalab/core/secure/xss/meta/Xss.java
- core/secure/src/main/java/me/nalab/core/secure/xss/meta/XssFiltering.java
- core/secure/src/main/java/me/nalab/core/secure/xss/spi/XssFilter.java
- core/secure/src/main/java/module-info.java
- core/secure/src/test/java/me/nalab/core/secure/xss/XssFilterAopRegisterTest.java
- core/secure/src/test/java/me/nalab/core/secure/xss/XssFilterTarget.java
- core/secure/src/test/java/me/nalab/core/secure/xss/XssTestFilter.java
- core/secure/src/test/java/me/nalab/core/secure/xss/json/JsonXssFilterTest.java
- core/secure/src/test/java/me/nalab/core/secure/xss/json/Request.java
- core/secure/src/test/java/me/nalab/core/secure/xss/json/RequestWrapper.java
- coverage-exclude.luffy
- survey/web-adaptor/build.gradle
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/FeedbackCreateController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/SurveyCreateController.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/ChoiceFormQuestionRequest.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/ShortFormQuestionRequest.java
- survey/web-adaptor/src/main/java/module-info.java
xss 공격을 방어하는 기능을 추가했습니다.
close #247
> [feat] : xss protect 추가

- Dockerfile
> [hoxfix] dockerfile 오타 수정

- Dockerfile
> [release] dockerfile 오타 수정

- .github/workflows/docker-publisher.yml
- Dockerfile
- api/build.gradle
- api/src/main/resources/application.properties
- api/src/main/resources/logback-spring.xml
- core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/advice/AuthorizationExceptionAdvice.java
- core/exception-handler/src/main/java/me/nalab/core/exception/handler/ValidationControllerAdvice.java
- survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/advice/FeedbackControllerAdvice.java
- sentry, logback 설정을 추가합니다.
- 기존과의 차이점은 따로 코멘트 추가해두었습니다!
> [infra] sentry, logback 설정 추가

- api/src/main/java/me/nalab/api/sentry/SentryController.java
- coverage-exclude.luffy
> [fix] sentry controller 추가

- gradle.properties
- support/logging/build.gradle
- 잘못된 sentry logback version을 수정합니다
> [fix] sentry logback version 수정

- .github/workflows/start-stage-server.yml
stage-server-start action에 sudo 옵션 추가
> [chore] : stage-server-start action에 sudo 옵션 추가

- support/e2e/survey_create.hurl
survey를 생성하고 검증하는 e2e 테스트를 부착했습니다.
resolve #273 
https://hurl.dev
> [test] : survey 생성 e2e 테스트

- support/e2e/feedback_create.hurl
feedback을 생성하는 e2e 테스트를 만들었습니다.
resolve #274 
https://hurl.dev
> [test] : feedback 생성 e2e 테스트

- survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
- survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
- survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java
- survey/survey-domain/src/test/java/me/nalab/survey/domain/AbstractTargetSources.java
- survey/survey-domain/src/test/java/me/nalab/survey/domain/feedback/FeedbackDomainTest.java
- survey/survey-domain/src/test/java/me/nalab/survey/domain/target/TargetDomainTest.java
feedback domain에 `bookmark domain` 을 추가했습니다.
- close #288
> [feat] : `bookmark`, `target position` 도메인 업데이트

- api/src/main/resources/db/migration/V6__bookmarked_at_not_null.sql
- core/data/src/main/java/me/nalab/core/data/feedback/FormFeedbackEntity.java
formfeedbackentity의 bookmarkedAt 필드에 not null 제약조건을 추가하고,
flyway에 업데이트 변경사항을 v6로 추가하였습니다
> [feat] : flyway v6 업데이트

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/TargetPositionUpdateAcceptanceTest.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/request/RequestSample.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/request/TargetPositionUpdateRequest.java
**로그인된 타겟의 정보 수정** API에 대한 인수테스트를 작성했습니다
> [feat] : 로그인된 타겟의 정보 수정 - `인수테스트` 작성

- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
- coverage-exclude.luffy
- survey/survey-application/src/main/java/module-info.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/updatetarget/TargetPositionUpdateController.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/updatetarget/request/TargetPositionUpdateRequest.java
> [feat] : 로그인된 타겟의 정보 수정 - `web-adaptor` 구현 완료

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/findtarget/TargetFindAcceptanceTest.java
- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java
- auth/auth-mock/src/main/java/me/nalab/auth/mock/interceptor/MockAuthInterceptor.java
- auth/auth-mock/src/test/java/me/nalab/auth/mock/interceptor/MockAuthInterceptorTest.java
- coverage-exclude.luffy
- survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findtarget/TargetFindBySurveyIdUseCase.java
- survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findtarget/TargetFindPort.java
- survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findtarget/TargetIdFindPort.java
- survey/survey-application/src/main/java/me/nalab/survey/application/service/findtarget/TargetFindBySurveyIdService.java
- survey/survey-application/src/main/java/module-info.java
- survey/survey-application/src/test/java/me/nalab/survey/application/service/findtarget/TargetFindBySurveyIdServiceTest.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/TargetFindAdaptor.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/TargetIdFindAdaptor.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/repository/TargetFindJpaRepository.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/repository/TargetIdFindJpaRepository.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TargetFindAdaptorTest.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TargetIdFindAdaptorTest.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TestTargetFindJpaRepository.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TestTargetIdFindJpaRepository.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findtarget/TargetFindBySurveyIdController.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findtarget/TargetResponseMapper.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findtarget/response/TargetResponse.java
`질문폼에 해당하는 타겟의 정보 조회` 기능 개발을 완료했습니다
- closes #322
> [feat] : `질문폼에 해당하는 타겟의 정보 조회` 기능 개발 완료

- support/e2e/v1_5_target.hurl
`로그인된 타겟의 정보 수정(인증O)`, `질문폼에 해당하는 타겟의 정보 조회(인증X)` 새로 추가된 두 API에 대한 e2e test를 추가하였습니다.
과정은 다음과 같이 진행됩니다.
* 회원가입을 한다
* 발급받은 토큰으로 survey를 생성한다
* 로그인된 타겟의 정보를 수정한다 - `로그인된 타겟의 정보 수정(인증O)`
* survey-id를 이용해 수정된 타겟의 정보를 확인한다 - `질문폼에 해당하는 타겟의 정보 조회(인증X)`
> [test] : e2e test v1_5 추가

- support/e2e/v1_4_bookmark.hurl
> [test] : `북마크 추가, 삭제 및 조회` e2e 테스트 추가

- survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/existsurvey/SurveyExistUseCase.java
- survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/existsurvey/SurveyExistCheckPort.java
- survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/existsurvey/SurveyExistPort.java
- survey/survey-application/src/main/java/me/nalab/survey/application/service/existsurvey/SurveyExistService.java
- survey/survey-application/src/test/java/me/nalab/survey/application/service/existsurvey/SurveyExistServiceTest.java
survey 존재 유무 확인 usecase를 추가했습니다.
> [feat] : survey 존재 유무 확인 `Use case` 추가

- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
- auth/auth-mock/src/main/java/me/nalab/auth/mock/config/MockAuthConfigurer.java
- coverage-exclude.luffy
- survey/survey-application/src/main/java/module-info.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/existsurvey/SurveyExistController.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/existsurvey/response/SurveyExistResponse.java
> [feat] : survey 존재 유무 확인 - `web-adaptor` 구현 완료

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/exists/SurveyExistsAcceptanceTest.java
- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
- auth/auth-mock/src/main/java/me/nalab/auth/mock/config/MockAuthConfigurer.java
- coverage-exclude.luffy
- support/e2e/v1_5_target.hurl
- survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/existsurvey/SurveyExistUseCase.java
- survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/existsurvey/SurveyExistPort.java
- survey/survey-application/src/main/java/me/nalab/survey/application/service/existsurvey/SurveyExistService.java
- survey/survey-application/src/main/java/module-info.java
- survey/survey-application/src/test/java/me/nalab/survey/application/service/existsurvey/SurveyExistServiceTest.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/existsurvey/SurveyExistAdaptor.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/existsurvey/repository/SurveyFindRepository.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/SurveyExistAdaptorTest.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/TestSurveyFindRepository.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/TestTargetRepository.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/existsurvey/SurveyExistController.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/existsurvey/response/SurveyExistResponse.java
`survey 존재 유무 확인` 기능 개발을 완료했습니다
- closes #344
> [feat] : `survey 존재 유무 확인` 기능 개발 완료

- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
- api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/exists/SurveyExistsAcceptanceTest.java
- auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
- auth/auth-mock/src/main/java/me/nalab/auth/mock/config/MockAuthConfigurer.java
- coverage-exclude.luffy
- support/e2e/v1_5_target.hurl
- survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/existsurvey/SurveyExistUseCase.java
- survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/existsurvey/SurveyExistPort.java
- survey/survey-application/src/main/java/me/nalab/survey/application/service/existsurvey/SurveyExistService.java
- survey/survey-application/src/main/java/module-info.java
- survey/survey-application/src/test/java/me/nalab/survey/application/service/existsurvey/SurveyExistServiceTest.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/existsurvey/SurveyExistAdaptor.java
- survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/existsurvey/repository/SurveyFindRepository.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/SurveyExistAdaptorTest.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/TestSurveyFindRepository.java
- survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/TestTargetRepository.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/existsurvey/SurveyExistController.java
- survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/existsurvey/response/SurveyExistResponse.java
> [feat] : `survey 존재 유무 확인` api 추가

- gallery/src/main/kotlin/me/nalab/gallery/app/GalleryGetApp.kt
- gallery/src/main/kotlin/me/nalab/gallery/controller/GalleryController.kt
- gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryService.kt
gallery 도메인 조회 오타 수정 및 lowercase를 uppercase로 변경했습니다.
- close #391
> [fix] : gallery 조회 order-type job -> BOOKMARK 및 조회 인자 uppercase로 변경
