depromeet/na-lab-server

.github/workflows/jacoco-reports.yml
api/acceptance-test/src/test/java/me/nalab/api/acceptancetest/jacoco/JacocoTest.java

jacoco-reports.yml 의 버전을 업그레이드 했습니다.
[actions/checkout](https://github.com/actions/checkout)   
[actions/setup-java](https://github.com/actions/setup-java#supported-distributions)

[Set up]  jacoco-reports CI 버전 업그레이드

---

api/acceptance-test/build.gradle
api/build.gradle

기존의 `api -> acceptance-test` 로 가던 dependency를 `api <- acceptance-test` 로 수정했습니다.
[NOTION의 아키텍처 결정사항](https://www.notion.so/depromeet/207940cf46124f7ba2e58ef4d8a1eabd?pvs=4)

[chore] api / acceptance-test dependency 수정

---

build.gradle

Jacoco test code coverage check에 `branch` rule을 추가 했습니다. 
[NOTION 기술문서](https://www.notion.so/depromeet/Test-Coverage-BRANCH-Counter-9862797c6e0441a894248683988bc0d1?pvs=4)
[Jacoco Coverage Counter 공식 문서](https://www.eclemma.org/jacoco/trunk/doc/counters.html)

[chore] Jacoco branch rule 70%

---

build.gradle
support/jacoco/build.gradle

새로운 모듈을 만들면, support/jacoco/build.gradle에 `implementation project('새로운 모듈')` 이런 방식으로 등록해줘야 하는 불편함을 없애기 위해, 새로운 모듈을 자동으로 감지해서 Test coverage를 측정하도록 수정했습니다.

[chore] Jacoco Test Coverage 새로운 모듈 감지 자동화

---

core/id-generator/id-generator-starter/build.gradle
core/id-generator/mock-id-generator/src/main/java/module-info.java
survey/application/build.gradle

`id-generator-starter` 를 의존받아도, id-core를 사용할 수 없는 버그를 수정했습니다.
build때, `module-info` 에서 `id-generator-starter` 관련 dependency warning이 뜨는 버그를 수정했습니다.
[gradle api vs implementation](https://kotlinworld.com/317#implementation%EA%B-%BC%C-%A-%--api%-C%--compile)

[fix] Id generator dependency

---

core/id-generator/id-generator-starter/src/main/java/module-info.java

id-generator-core에 대한 의존성이, 사용자에게 전이 되도록 수정했습니다.
[jigsaw project](https://www.baeldung.com/java-9-modularity)

[fix] `id-generator-core` 에 대한 의존성 전이

---

settings.gradle
survey/domain/.gitignore
survey/domain/src/main/java/me/nalab/survey/domain/survey/Choice.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestionType.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/QuestionType.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ShortFormQuestion.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ShortFormQuestionType.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/Survey.java
survey/domain/src/main/java/me/nalab/survey/domain/target/Target.java
survey/domain/src/main/java/module-info.java
survey/domain/src/test/java/me/nalab/survey/domain/AbstractSurveySources.java
survey/domain/src/test/java/me/nalab/survey/domain/AbstractTargetSources.java
survey/domain/src/test/java/me/nalab/survey/domain/survey/AbstractSurveyDomainTest.java
survey/domain/src/test/java/me/nalab/survey/domain/target/TargetDomainTest.java

[feat] `Survey` domain model

---

survey/domain/src/main/java/me/nalab/survey/domain/survey/Choice.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ShortFormQuestion.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/Survey.java
survey/domain/src/main/java/me/nalab/survey/domain/target/Target.java

`Survey` 도메인의 `equals` `hashCode` `toString` 메소드를 구현에서 lombok으로 적용했습니다.

[fix] : `Survey` domain `equals` `hashCode` `toString` lombok 적용

---

settings.gradle
survey/application/build.gradle
survey/application/src/main/java/me/nalab/survey/application/port/in/create/CreateSurveyUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/in/create/request/CreateChoice.java
survey/application/src/main/java/me/nalab/survey/application/port/in/create/request/CreateChoiceQuestion.java
survey/application/src/main/java/me/nalab/survey/application/port/in/create/request/CreateQuestionable.java
survey/application/src/main/java/me/nalab/survey/application/port/in/create/request/CreateShortQuestion.java
survey/application/src/main/java/me/nalab/survey/application/port/in/create/request/CreateSurveyRequest.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/CreateSurveyPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/FindTargetPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceChoice.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceChoiceFormQuestion.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceChoiceFormQuestionType.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceFormQuestionable.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceQuestionType.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceShortFormQuestion.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceShortFormQuestionType.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceSurveyRequest.java
survey/application/src/main/java/module-info.java
survey/application/src/test/java/me/nalab/survey/application/TestIdGenerator.java
survey/application/src/test/java/me/nalab/survey/application/fixture/CreateSurveyFixture.java
survey/application/src/test/java/me/nalab/survey/application/port/in/create/CreateSurveyRequestTest.java
survey/application/src/test/java/me/nalab/survey/application/port/out/create/CreatePersistenceSurveyEnumTest.java

Survey create usecase의 `in.port`와 `out.port`를 정의하고, port별 `Request Dto` 를 만들었습니다.
__질문폼 생성 usecase의 port별 dto가 많아서.. PR이 너무 커져 port 인터페이스와 request만 따로 올립니다..!__
dto는 `lombok` 으로 `Builder` `Getter` `EqualsAndHashCode` `ToString` 만 정의 되어있는게 대부분이라 빠르게 넘겨도 될거같고 
인터페이스랑 테스트코드 위주로 봐주시면 될거 같습니다.
dto 특이점 으로는..
out.port의 requestDto에서, enum 타입인, [`PersistenceQuestionType`](survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceQuestionType.java), [`PersistenceChoiceFormQuestionType`](survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/request/PersistenceChoiceFormQuestionType.java), [`PersistenceShortFormQuestionType`](survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/create/requ …

[feat] : Survey create usecase `port`

---

core/data/build.gradle
core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestion.java
core/data/src/main/java/me/nalab/core/data/target/Target.java
core/data/src/main/java/module-info.java

`Entity`가 위치한 `data` 모듈에서, 더 이상 사용하지 않는 의존성을 삭제하고, `Entity class`간 어노테이션 순서를 맞췄습니다

[fix] : `data` 모듈 청소

---

core/data/src/main/java/me/nalab/core/data/survey/ChoiceEntity.java
core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestionEntity.java
core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestionEntityType.java
core/data/src/main/java/me/nalab/core/data/survey/FormQuestionEntity.java
core/data/src/main/java/me/nalab/core/data/survey/QuestionEntityType.java
core/data/src/main/java/me/nalab/core/data/survey/ShortFormQuestionEntity.java
core/data/src/main/java/me/nalab/core/data/survey/ShortFormQuestionEntityType.java
core/data/src/main/java/me/nalab/core/data/survey/SurveyEntity.java
core/data/src/main/java/me/nalab/core/data/target/TargetEntity.java

jpa-entity 클래스와 domain 클래스의 이름이 같아. 변환시 한쪽을 `public Survey toSurvey (me.nalab.core.data.Survey survey){...}` 와 같이 사용해야하는 문제점이 있어, JpaEntity에 -Entity 접미사를 추가했습니다.

[fix] : `JpaEntity` 클래스에 -Entity 접미사 추가

---

survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/survey/find/SurveyFindPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/target/find/TargetFindPort.java
survey/application/src/main/java/me/nalab/survey/application/service/survey/find/SurveyFindService.java
survey/application/src/main/java/me/nalab/survey/application/service/target/find/TargetFindService.java
survey/application/src/main/java/module-info.java
survey/application/src/test/java/me/nalab/survey/application/RandomSurveyDtoFixture.java
survey/application/src/test/java/me/nalab/survey/application/service/survey/find/SurveyFindServiceTest.java
survey/application/src/test/java/me/nalab/survey/application/service/target/find/TargetFindServiceTest.java

질문 폼 조회 application의 persistence 쪽으로 나가는 port의 반환 타입이 틀렸었습니다
jaa-adaptor 쪽을 구현하다가 알아차리고 다시 급하게 수정하였습니다
반환타입은 도메인이어야합니다.
도메인으로 변경하고, 해당 service의 테스트코드도 수정이 많이 일어나 테스트코드도 거의 다시 짰습니다

[feat] : 질문 폼 조회 application의 port 인터페이스 수정

---

core/data/src/main/java/me/nalab/core/data/survey/ChoiceEntity.java
core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestionEntity.java
core/data/src/main/java/me/nalab/core/data/survey/FormQuestionEntity.java
core/data/src/main/java/me/nalab/core/data/survey/SurveyEntity.java

`@Entity`의 column명을 수정하고, Cascade정책을 추가 했습니다.

[fix] : `@Entity`의 column이름 수정 및 cascade정책

---

core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestionEntity.java
core/data/src/main/java/me/nalab/core/data/survey/SurveyEntity.java

`@Entity` 생성시, 자식에게 `FK auto set` 이 안되는 문제를 수정했습니다.

[fix] : `@Entity` 생성시, 자식에게 `FK auto set` 이 안되는 문제

---

survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/LatestSurveyIdFindPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/SurveyCreatePort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/TargetExistCheckPort.java
survey/application/src/main/java/me/nalab/survey/application/service/create/LatestSurveyIdFindService.java
survey/application/src/main/java/me/nalab/survey/application/service/create/SurveyCreateService.java
survey/application/src/test/java/me/nalab/survey/application/service/create/LatestSurveyIdFindServiceTest.java
survey/application/src/test/java/me/nalab/survey/application/service/create/SurveyCreateServiceTest.java
survey/jpa-adaptor/build.gradle
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/create/LatestSurveyIdFindAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/create/SurveyCreateAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/create/TargetExistCheckAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/create/repository/SurveyCreateJpaRepository.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/create/repository/TargetExistJpaRepository.java
survey/jpa-adaptor/src/main/java/module-info.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/create/LatestSurveyIdFindAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/create/SurveyCreateAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/create/TargetExistCheckAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/create/TestSurveyJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/create/TestTargetJpaRepository.java
survey/jpa-adaptor/src/test/resources/h2.properties

Survey를 생성하는 usecase의 `jpa-apdaptor`를 추가했습니다.

[feat] : Survey create usecase 관련된 `jpa-adaptor` 추가

---

survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findid/SurveyIdFindPort.java
survey/application/src/main/java/me/nalab/survey/application/service/getid/SurveyIdGetService.java
survey/application/src/main/java/module-info.java
survey/application/src/test/java/me/nalab/survey/application/service/getid/SurveyIdGetServiceTest.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findid/SurveyIdFindAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findid/repository/SurveyIdFindJpaRepository.java
survey/jpa-adaptor/src/main/java/module-info.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findid/SurveyIdFindAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findid/TestSurveyJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findid/TestTargetJpaRepository.java

survey id 유즈케이스에서 사용하는 `jpa-adaptor`를 추가했습니다.

[feat] : survey id 유즈케이스  `jpa-adaptor` 추가

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/DatabaseCleaner.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/TargetInitializer.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/TestEntryPoint.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/RequestSample.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/SurveyCreateAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/dto/ChoiceFormQuestionRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/dto/ChoiceRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/dto/FormQuestionRequestable.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/dto/ShortFormQuestionRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/dto/SurveyCreateRequest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/survey/find/mapper/SurveyFindResponseMapper.java

survey를 생성하는 인수테스트를 작성했습니다.
accept-template에 버그들을 수정했습니다.

[feat] :  `create-survey` 인수테스트 작성 및 버그 수정

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/RequestSample.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/dto/ChoiceFormQuestionRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/dto/ChoiceRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/dto/FormQuestionRequestable.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/dto/ShortFormQuestionRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/dto/SurveyCreateRequest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/findid/SurveyFindidAcceptanceTest.java

로그인된 타겟의 survey id를 찾는 인수테스트를 작성했습니다.

[feat] : logined target survey id find `인수 테스트` 작성

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/RequestSample.java
core/data/src/main/java/me/nalab/core/data/survey/ChoiceFormQuestionEntityType.java
survey/application/src/main/java/me/nalab/survey/application/common/dto/ChoiceFormQuestionDtoType.java
survey/application/src/test/java/me/nalab/survey/application/common/dto/CommonDtoEnumTest.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestionType.java
survey/web-adaptor/src/test/java/me/nalab/survey/web/adaptor/createsurvey/TestJson.java

`position` 과 `collaboration-experience` enum을 도메인, dto, entity에서 삭제했습니다.

[refactor] : `position`, `collaboration-experience ` enum 삭제

---

core/exception-handler/build.gradle
core/exception-handler/src/main/java/me/nalab/core/exception/handler/ErrorTemplate.java
core/exception-handler/src/main/java/me/nalab/core/exception/handler/ValidationControllerAdvice.java
core/exception-handler/src/main/java/module-info.java
core/exception-handler/src/test/java/me/nalab/core/exception/handler/TestController.java
core/exception-handler/src/test/java/me/nalab/core/exception/handler/TestRequest.java
core/exception-handler/src/test/java/me/nalab/core/exception/handler/ValidationControllerAdviceTest.java
settings.gradle

`javax.validation` 예외를 처리하는 전역 예외 핸들러를 추가했습니다.

[feat] : `javax.validation` 전역 예외 핸들러 추가

---

survey/application/src/main/java/me/nalab/survey/application/service/find/SurveyFindService.java
survey/application/src/test/java/me/nalab/survey/application/service/find/SurveyFindServiceTest.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/Choice.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/ChoiceFormQuestion.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/FormQuestionable.java
survey/domain/src/main/java/me/nalab/survey/domain/survey/Survey.java
survey/domain/src/test/java/me/nalab/survey/domain/AbstractSurveySources.java
survey/domain/src/test/java/me/nalab/survey/domain/AbstractTargetSources.java
survey/domain/src/test/java/me/nalab/survey/domain/survey/ChoiceTest.java
survey/domain/src/test/java/me/nalab/survey/domain/survey/FormQuestionableTest.java
survey/domain/src/test/java/me/nalab/survey/domain/survey/SurveyDomainTest.java

질문 폼 조회 usecase에
survey 반환 시에, survey의 모든 질문들을 지정된 order에 맞게 반환하는 로직을 추가했습니다

[fix] : 질문 폼 조회 usecase에서 questions반환 시 order로 정렬한 후 반환하는 로직 추가

---

survey/application/src/main/java/me/nalab/survey/application/port/in/web/createfeedback/FeedbackCreateUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/createfeedback/FeedbackSavePort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/createfeedback/ReviewerLatestNameFindPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/createfeedback/SurveyFindPort.java
survey/application/src/main/java/me/nalab/survey/application/service/createfeedback/FeedbackCreateService.java
survey/application/src/test/java/me/nalab/survey/application/RandomFeedbackDtoFixture.java
survey/application/src/test/java/me/nalab/survey/application/TestIdGenerator.java
survey/application/src/test/java/me/nalab/survey/application/service/createfeedback/FeedbackCreateServiceTest.java

feedback을 survey에 추가하는 유즈케이스를 개발했습니다.

[feat] : `Feedback 생성` 유즈케이스 추가

---

survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/FeedbackCountAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/repository/FeedbackCountJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/TestFeedbackCountJpaRepository.java

`FeedbackCountJpaRepository` 에서 getResultList가 아닌 countBy로 한 번에 counting한 값을 가져오도록 변경하였습니다

[fix] : 질문 폼의 요약정보 조회 유즈케이스 `jpa-adaptor` FIX

---

survey/application/src/main/java/me/nalab/survey/application/port/in/web/feedbacksummary/FeedbackSummaryFindUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbacksummary/TotalFeedbackCountPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbacksummary/UpdatedFeedbackCountPort.java
survey/application/src/main/java/me/nalab/survey/application/service/findfeedbacksummary/FeedbackSummaryFindService.java
survey/application/src/test/java/me/nalab/survey/application/service/findfeedbacksummary/FeedbackSummaryFindServiceTest.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/FeedbackCountAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/repository/FeedbackCountJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/FeedbackCountAdaptorTest.java

질문 폼 요약정보 application 쪽 포트인 `TotalFeedbackCountPort` 와 `UpdatedFeedbackCountPort` 의 반환타입을 int -> long 타입으로 바꿨습니다!
이유는 jpa에서 countBy 가 long을 반환하기 때문입니다.
바뀐 부분이 두 모듈에서 있고, web-adpator쪽에서도 변경된 사항을 기반으로 개발을 해야할 것 같아 따로 올렸습니다..!!
이후 web-adaptor쪽에서 response로 매핑할 때에 int로 변환할 예정입니다

[refactor] : 중간 코드 리팩토링

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findsummary/FeedbackFindSummaryAcceptanceTest.java

질문 폼의 피드백 요약 (해당 전체 피드백 수와 읽지 않은 피드백의 수) API에 대한 인수테스트를 작성했습니다

[test] : 질문 폼의 피드백 요약 인수테스트 작성

---

coverage-exclude.luffy
survey/application/src/main/java/module-info.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbacksummary/FeedbackSummaryController.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbacksummary/response/FeedbackSummaryResponse.java

질문 폼의 요약정보 조회 유즈케이스의 `web-adaptor` 를 구현하였습니다
* 질문 폼의 요약정보 조회의 control class인 FeedbackSummaryController를 추가했습니다
* 반환할 객체 FeedbackSummaryResponse를 추가했습니다

[feat] : 질문 폼의 요약정보 조회 유즈케이스 `web-adaptor` 구현

---

survey/application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/FeedbackFindUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/FeedbackFindPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/SurveyExistCheckPort.java
survey/application/src/main/java/me/nalab/survey/application/service/findfeedback/FeedbackFindService.java
survey/application/src/test/java/me/nalab/survey/application/service/findfeedback/FeedbackFindServiceTest.java
survey/domain/src/main/java/me/nalab/survey/domain/feedback/Feedback.java
survey/domain/src/test/java/me/nalab/survey/domain/feedback/FeedbackDomainTest.java

surveyId에 해당하는 feedback 정보 조회 유즈케이스를 추가했습니다.

[feat] : surveyId에 해당하는 feedback 정보 조회 유즈케이스

---

core/data/src/main/java/me/nalab/core/data/feedback/FeedbackEntity.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/FeedbackFindPort.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/SurveyExistCheckPort.java
survey/application/src/main/java/module-info.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/FeedbackFindAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/repository/FeedbackFindRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/FeedbackFindAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/TestFeedbackJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/TestSurveyJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/TestTargetJpaRepository.java

feedback find 유즈케이스의 jpa adaptor를 추가했습니다.

[feat] : feedback find 유즈케이스 `jpa adaptor 추가`

---

.github/workflows/accept-analyze.yml

main push에 대해서, sonar analyze가 수행되지않아, sonar cloud 분석 리포트가 업데이트 되지 않고있어서, sonar analyze가 main에서도 돌아가게 만들었습니다.

[chore] : sonar analyze main 에서 돌아가게 수정

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findreviewers/ReviewersFindAcceptanceTest.java

질문 폼의 모든 리뷰어 조회 API에 대한 인수테스트를 작성했습니다
* 피드백이 하나도 없는 경우일때 , 피드백이 하나라도 있는 경우일 때 두 가지로 나누어서 검증을 하였습니다

[feat] : 질문 폼의 모든 리뷰어 조회- 인수테스트 작성

---

coverage-exclude.luffy
survey/application/src/main/java/me/nalab/survey/application/port/in/web/feedbackreviewers/FeedbackReviewersFindUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbackreviewers/FeedbacksFindPort.java
survey/application/src/main/java/me/nalab/survey/application/service/feedbackreviewers/FeedbackReviewersFindService.java
survey/application/src/main/java/module-info.java
survey/application/src/test/java/me/nalab/survey/application/service/feedbackreviewers/FeedbackReviewersFindServiceTest.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/repository/FeedbackFindJpaRepository.java
survey/jpa-adaptor/src/main/java/module-info.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/FeedbacksReviewersAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/TestFeedbackFindJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/feedbackreviewers/TestSurveyCreateJpaRepository.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersController.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersResponseMapper.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/FeedbackReviewer.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/FeedbackReviewersResponse.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/feedbackreviewers/response/ReviewerResponse.java
survey/web-adaptor/src/test/java/me/nalab/survey/web/adaptor/feedbackreviewers/FeedbackReviewersResponseMapperTest.java

[feat] : 질문 폼의 모든 리뷰어 목록 조회 `application`,  `jpa-adaptor`, `web-adaptor` 구현 

---

core/id-generator/id-generator-starter/build.gradle
core/id-generator/id-generator-starter/src/main/java/me/nalab/core/idgenerator/starter/IdGeneratorConfigurer.java
core/id-generator/id-generator-starter/src/main/java/module-info.java
core/id-generator/tsid/build.gradle
core/id-generator/tsid/src/main/java/me/nalab/core/idgenerator/tsid/TsidGenerator.java
core/id-generator/tsid/src/main/java/me/nalab/core/idgenerator/tsid/engine/TsidEngine.java
core/id-generator/tsid/src/main/java/module-info.java
core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/DefaultTsidActor.java
core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/ThreadTsidActor.java
core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/TsidConfigurer.java
core/id-generator/tsid/src/test/java/me/nalab/core/idgenerator/tsid/TsidPerformanceTest.java
coverage-exclude.luffy
settings.gradle

Id Generator로 `TSID(Time Sorted Id Generator)` 를 추가했습니다.
`TSID?`
twitter의 snowflake 알고리즘과 ulid를 기반으로 만들어 졌다고 하는데요
`(__________) (_____) (________)`
`( timestamp ) ( node ) (sequential)` 
로 이루어져있고(snowflake랑 차이는 모르겠음), 벤치마킹과 스타가 준수하길래 이거로 가져왔습니다.
(1024, 4096 까지 가능은 한데, 그럼 성능이 내려가서 256으로 만들었어요 나중에 저희 서비스가 동접 256뚫으면 늘리면 될듯? 합니다)
(이제, 모든 테스트가 이 generator 기반으로 돌아갑니다.) 
[TSID library](https://github.com/f4b6a3/tsid-creator)

[feat] : TSID id generator 추가

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findspecific/SpecificFindAcceptanceTest.java

개별 피드백에 대한 응답 조회 API에 대한 인수테스트를 작성했습니다

[feat] : 개별 피드백 응답 조회 - `인수테스트` 작성

---

survey/application/src/main/java/module-info.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackFindAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/SurveyFindAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/repository/FeedbackFindJpaRepository.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/repository/SurveyFindJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackFindAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/SurveyFindAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/TestFeedbackFindJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/TestSurveyFindJpaRepository.java

개별 피드백에 대한 응답 조회 API에 대한 jpa-adaptor 부분을 개발 완료했습니다

[feat] : 개별 피드백 응답 조회 - `jpa-adaptor` 구현 완료

---

coverage-exclude.luffy
gradle/sonar.gradle

sonar cloud에서 exclude 안되는 문제를 해결...🙏 했습니다.
저희 exclude가 계속 안고쳐져서.. main 브랜치에서 커버리지 `69퍼`로 ci fail이 뜨더군요..(실제 커버리지는 95%) exclude.luffy에 넣으면 자동으로 sonar 커버리지에서 제외되도록 만들고 있는데.. 정 안되면 sonarcloud에 수동으로 해야할거 같습니다 
이거도 다른 브랜치 기능에 영향을 미치지는 않아서.. `squash merge` 하겠습니다.

[fix] : sonar cloud에서 exclude 안되는 문제

---

.github/workflows/docker-publisher.yml
.github/workflows/release-labeler.yml

Docker image를 생성하고, Docker hub에 등록하는 workflow를 만들었습니다.
release PR의 경우 release 라벨이 붙도록 설정했습니다.
추후에, `default branch`는 `main`에서 `release`로 변경해야할거 같아요
ex. `release tag v0.0.1` -> `samillmu/luffy:v0.0.1`
저희 release로 버전관리 하는거로 알고 있어서, release에 publish 되는 시점에 아래 flow처럼 만들려고 합니다..! 한번만 확인해주세요
`새로운 release 생성 및 태그 등록` -> `docker hub에 이미지 등록 CI` -> `code deploy CI` -> `실행`
[github publish image to dockerhub and github package](https://docs.github.com/ko/actions/publishing-packages/publishing-docker-images)
[docker metadata action](https://github.com/marketplace/actions/docker-metadata-action)
[docker build and push action](https://github.com/marketplace/actions/build-and-push-docker-images)
[docker login action](https://github.com/marketplace/actions/docker-login)
[이 PR 테스트 과정에서 등록된 우리의 docker …

[chore] : Docker image publisher 생성

---

coverage-exclude.luffy
settings.gradle
user/user-application/src/main/java/me/nalab/user/application/common/dto/LoginedInfo.java
user/user-application/src/main/java/me/nalab/user/application/port/in/LoginedUserGetByTokenUseCase.java
user/user-web-adaptor/build.gradle
user/user-web-adaptor/src/main/java/me/nalab/user/web/adaptor/logined/LoginedUserGetController.java
user/user-web-adaptor/src/main/java/me/nalab/user/web/adaptor/logined/response/LoginedInfoResponse.java

login 된 유저를 조회하는 컨트롤러를 추가했습니다.

[feat] : Login된 유저 조회 컨트롤러 추가

---

auth/auth-application/src/main/java/me/nalab/auth/application/common/dto/Payload.java
auth/auth-application/src/main/java/me/nalab/auth/application/service/JwtLoginedDecryptService.java
auth/auth-application/src/test/java/me/nalab/auth/application/service/JwtLoginedDecryptServiceTest.java
user/user-application/src/main/java/me/nalab/user/application/common/dto/LoginedInfo.java
user/user-application/src/main/java/me/nalab/user/application/port/out/persistence/LoginedUserGetByTokenPort.java

JWT를 복호화해서 로그인된 유저를 추출하는 기능 추가
근데 슬랙에 올라와있는 property 이슈로 막혀있어요 ㅠㅠ 도진님 수정 pr 올라오면 나중에 merge 받고 squash 할깨용

[feat] : JWT로 로그인된 유저 조회 기능 추가

---

survey/application/src/main/java/me/nalab/survey/application/port/in/web/findspecific/SpecificFindUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/findspecific/FeedbackUpdatePort.java
survey/application/src/main/java/me/nalab/survey/application/service/findspecific/SpecificFindService.java
survey/application/src/test/java/me/nalab/survey/application/service/findspecific/SpecificFindServiceTest.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackUpdateAdaptor.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findspecific/FeedbackUpdateAdaptorTest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findspecific/SpecificFeedbackController.java

읽음처리를 수행하는 부분은 다음의 두 부분입니다
[  `피드백에 대한 읽음 처리` ,  `피드백 각 문항에 대한 읽음 처리` ]
이 둘 중 (피드백 리스트에서) `피드백에 대한 읽음 처리`를 먼저 구현했습니다
해당 부분은 다음과 같습니다
해당 기능은  `리뷰어의 개별 응답 조회`를 하였을 때에 피드백의 isRead 가 변경되도록 구현하였습니다

[feat] : 리뷰어 개별 응답 목록에서 피드백 읽음처리 기능 추가 (#186)

---

core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java

cors 호출시 Header 제한에 Location이 걸려있는 버그 수정

[fix] : cors 호출시 header 제한 제거 핫픽스

---

auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java
core/secure/src/main/java/me/nalab/core/secure/CorsConfig.java

cors 설정에 credentials를 넣은걸 제외 했습니다.
> Origins가 `*` 면 credentials를 true로 할 수 없음.
[트러블 슈팅]
JwtInterceptor가 OPTIONS메소드에 대해서도 적용되고 있었고, 인증이 필요한preflight에서 Authorization헤더가 비어있어 null pointer 예외가 발생한거 같습니다.
그래서, 응답으로 `500 Internal server error` + Cors 라는 조합이 뜬거 같아요

[fix] : delete credentials

---

auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java

[fix] : bearer 공백으로 제거

---

survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/feedbacksummary/SurveyExistCheckPort.java
survey/application/src/main/java/me/nalab/survey/application/service/findfeedbacksummary/FeedbackSummaryFindService.java
survey/application/src/test/java/me/nalab/survey/application/service/findfeedbacksummary/FeedbackSummaryFindServiceTest.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/SurveyExistCheckAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/repository/SurveyExistCheckJpaRepository.java

질문 폼의 피드백 요약정보 조회 API에서 예외처리가 빠져있는 부분을 수정했습니다
지금 예외처리 검토중인데 해당 부분의 예외처리가 빠져있어서 추가했습니다
- #194

[fix] : 질문 폼의 피드백 요약정보 조회 API에서 예외처리 추가

---

survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/SurveyExistCheckAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/repository/SurveyExistCheckJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/SurveyExistCheckAdaptorTest.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/TestSurveyJpaRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedbacksummary/TestTargetJpaRepository.java

`SurveyExistCheckAdaptor` 이름의 bean이 2개 있어서 충돌이 나는 버그를 수정했습니다.

[fix] : `SurveyExistCheckAdaptor` bean collision

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/FeedbackCreateAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findreviewers/ReviewersFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findspecific/SpecificFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/RequestSample.java
api/api-mock/src/main/java/me/nalab/api/mock/MockController.java
survey/application/src/test/java/me/nalab/survey/application/service/summaryreviewer/ReviewerSummaryGetServiceTest.java
survey/domain/src/test/java/me/nalab/survey/domain/feedback/FeedbackDomainTest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/ReviewerRequest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/ReviewerSummaryResponseMapper.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/summaryreviewer/response/PositionSummaryReponse.java

position naming을 전체적으로 변경했습니다.

[refactor] : position naming hotfix

---

api/src/main/resources/db/migration/V3__user_email_unique.sql
core/data/src/main/java/me/nalab/core/data/user/UserEntity.java

엔티티 `users.email` 에 `unique` 제약이 안걸려있어서, 동시성 이슈로 중복 유저가 생성되는 문제를 해결했습니다.

[refactor] : unique constraint to `users.email`

---

auth/auth-application/src/main/java/me/nalab/auth/application/service/SignInWithOAuthService.java
survey/application/src/main/java/me/nalab/survey/application/port/in/web/target/find/TargetFindByUsernameUseCase.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/target/find/TargetFindPort.java
survey/application/src/main/java/me/nalab/survey/application/service/TargetFindByUsernameService.java
survey/application/src/main/java/module-info.java
survey/application/src/test/java/me/nalab/survey/application/service/find/TargetFindByUsernameServiceTest.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/find/TargetFindAdaptor.java
survey/jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/find/repository/TargetFindRepository.java
survey/jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/find/TargetFindAdaptorTest.java

- 로그인 시 타겟을 생성하지 않고 기존의 타겟을 가져오도록 변경
- username 기반 target 조회 기능 구현 및 테스트 작성
- 회원 가입 시에 target에 생성되는 데도 불구하고 로그인 시에 해당 target 조회가 아닌 생성을 하고 있었음.
- 로그인 시에 생성 로직을 삭제, 조회 로직으로 변경

[fix] 로그인 시 target 생성 삭제 및 조회 기능 구현

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/auth/signin/SignInWithOAuthAcceptanceTest.java
auth/auth-application/src/test/java/me/nalab/auth/application/service/SignInWithOAuthServiceTest.java

- 로그인 시 회원 가입되어있다면 이미 생성된 target을 조회하는 로직 변경에 대한 테스트 초기화 반영
- 인수테스트에 기 구현된 TargetInitializer를 통해 유저와 함께 target 초기화 추가
- 단위 테스트에 모킹 추가

[hotfix] sign in 인수 test 타겟 초기화 추가

---

auth/auth-application/src/main/java/me/nalab/auth/application/service/SignInWithOAuthService.java

토큰 생성시, targetId가 아닌 targetDto가 암호화 되던 버그를 수정했습니다.

[fix] : 토큰생성시 잘못된 값 바인딩되던 버그 수정

---

survey/application/src/main/java/me/nalab/survey/application/service/getid/SurveyIdGetService.java
survey/application/src/test/java/me/nalab/survey/application/service/getid/SurveyIdGetServiceTest.java

survey가 여러개 생성되었을때, `/v1/surveys-id` api가 마지막 survey의 id를 반환하도록 수정했습니다.

[refactor] : survey가 여러개일시 마지막 값이 반환되도록 수정

---

core/authorization/authorization-aop/build.gradle
core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/AuthorizationAspect.java
core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/meta/Auth.java
core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/meta/Authorization.java
core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/util/ValidatorFactoryStorage.java
core/authorization/authorization-aop/src/main/java/module-info.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/AspectTarget.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/AuthorizationAspectTest.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/validator/LongValidExtractor.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/validator/LongValidator.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/validator/LongValidorFactory.java
settings.gradle

`@Authorization` 과 `@Auth` 어노테이션을 이용해 권한 검증을 진행하는 AOP를 추가했습니다.
사용예시
``` java
@Component
class AspectTarget {
// 예) Survey에 실 적용하면 SurveyValidatorFactory.class 적용
@Authorization(factory = LongValidorFactory.class) 
Long isArrived(@Auth Long id) {
return id;
}
@Authorization(factory = LongValidorFactory.class)
Long isArrived(@Auth Long id1, @Auth Long id2) {
return id1;
}
@Authorization(factory = LongValidorFactory.class)
Long isArrivedWithOutAuth(Long id) {
return id;
}
}
```

[feat] : `@Authorization` 어노테이션 기반 권한 검증 기능

---

core/authorization/authorization-aop/src/main/java/module-info.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/validator/LongValidExtractor.java
core/authorization/authorization-core/src/main/java/me/nalab/core/authorization/api/ParameterReference.java
core/authorization/authorization-core/src/main/java/me/nalab/core/authorization/api/WrongReferenceTypeException.java
core/authorization/authorization-core/src/main/java/me/nalab/core/authorization/engine/DefaultAuthorizerEngine.java
core/authorization/authorization-core/src/main/java/me/nalab/core/authorization/spi/ParameterExtractor.java
core/authorization/authorization-core/src/test/java/me/nalab/core/authorization/engine/ParameterReferenceTest.java
core/authorization/authorization-core/src/test/java/me/nalab/core/authorization/spi/AuthorizationSystemTest.java
core/authorization/authorization-core/src/test/java/me/nalab/core/authorization/validator/LongValidExtractor.java
core/authorization/authorization-core/src/test/java/me/nalab/core/authorization/validator/StringValidExtractor.java
coverage-exclude.luffy
survey/application/build.gradle
survey/application/src/main/java/me/nalab/survey/application/port/in/authorization/SurveyAuthorization.java
survey/application/src/main/java/me/nalab/survey/application/port/out/persistence/authorization/TargetIdFindPort.java
survey/application/src/main/java/me/nalab/survey/application/service/authorization/FeedbackIdValidator.java
survey/application/src/main/java/me/nalab/survey/application/service/authorization/FeedbackIdValidatorFactory.java
survey/application/src/main/java/me/nalab/survey/application/service/authorization/LongParameterExtractor.java
survey/application/src/main/java/me/nalab/survey/application/service/authorization/SurveyIdValidator.java
survey/application/src/main/java/me/nalab/survey/application/service/authorization/SurveyIdValidatorFactory.java
survey/application/src/main/java/module-info.java
survey/application/src/test/java/me/nalab/survey/application/service/authorization/FeedbackIdValidatorTest.java
survey/application/src/test/java/me/nalab/survey/application/service/authorization/SurveyIdValidatorTest.java

권한 인증 모듈의 surveyId와 feedbackId로 권한인증을 하는 기능을 확장했습니다.

[feat] : survey authorization validator 확장 정의

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/RequestSample.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/SurveyCreateAcceptanceTest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/FeedbackCreateController.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/ReviewerRequest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/request/ShortQuestionFeedbackRequest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/SurveyCreateController.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/ChoiceFormQuestionRequest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/FormQuestionRequestable.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/ShortFormQuestionRequest.java
survey/web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createsurvey/request/SurveyCreateRequest.java

질문 폼 생성, 질문 폼 응답 API controller 쪽에 @Valid 를 추가하여 requestBody 를 검증하도록 하였습니다
그리고 최근 업데이트 된 요구사항까지 추가하여 어노테이션을 부착하였습니다
- #223 
이거 테스트부분을 어떻게 추가해야할지 고민입니다...!!
일단 예시 하나만 추가했는데, 현재는 저희가 인수테스트 부분을 성공에 대한 코드만 작성을 해서
실패 부분에 대한 검증 테스트는 어디서 해야할지 얘기해보고 싶었습니다
아님 같은 web-adaptor 모듈의 테스트에 넣어야 할지?

[fix] : 질문폼생성, 응답 부분에 @Valid 검증 추가

---

core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/advice/AuthorizationExceptionAdvice.java
core/authorization/authorization-aop/src/main/java/me/nalab/core/authorization/aop/advice/ErrorTemplate.java
core/authorization/authorization-aop/src/main/java/module-info.java
core/authorization/authorization-aop/src/test/java/me/nalab/core/authorization/aop/AuthorizationAspectTest.java
core/authorization/authorization-core/src/main/java/me/nalab/core/authorization/api/CannotAuthorizationException.java
core/authorization/authorization-core/src/main/java/me/nalab/core/authorization/engine/DefaultAuthorizerEngine.java
coverage-exclude.luffy

권한 인증이 실패했을때, 해들링 하는 ControllerAdvice를 부착했습니다.
resolves #235

[feat] : authorization fail exception handler 추가

---

.github/workflows/docker-release-publisher.yml
.github/workflows/docker-stage-publisher.yml
.github/workflows/start-release-server.yml
.github/workflows/start-stage-server.yml

dev 서버용 ci,cd 액션 추가 및, 깃허브 시크릿을 설정했습니다.
close #269 
hikari maximum connection pool default size가 `0`이라고 하더라구요?? 
그래서 dev서버에 profile 만들어서 connection pool 줄이는 설정은 따로 안했고, release로 가는 cd에 github action 설정으로 connection pool 좀 늘려주는 방향으로 생각하고 있습니다
[springframework-guru](https://springframework.guru/hikari-configuration-for-mysql-in-spring-boot-2/)
https://springframework.guru/hikari-configuration-for-mysql-in-spring-boot-2/

[chore] : dev 서버용 secret 추가 및 ci,cd action 추가

---

api/src/main/resources/db/migration/V4__add_bookmark.sql
core/data/src/main/java/me/nalab/core/data/feedback/FormFeedbackEntity.java

2차 mvp에 추가되는 엔티티의 업데이트내용을 반영하고, flyway에 v4를 추가하였습니다
- 그리고 mapper 변경사항은 그리고 도메인, 엔티티 각 부분 merge후에 수정하면 될 것 같습니다.
- close #290

[feat] : target, bookmark 엔티티 업데이트 

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/BookmarkResponse.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/FormQuestionResponseable.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/dto/BookmarkDto.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/dto/FormQuestionFeedbackDtoable.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/mapper/FeedbackDtoMapper.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/dto/TargetDto.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/mapper/TargetDtoMapper.java
survey/survey-application/src/test/java/me/nalab/survey/application/RandomFeedbackDtoFixture.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/FeedbackEntityMapper.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/TargetEntityMapper.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/RandomFeedbackFixture.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptorTest.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/FeedbackCreateController.java

2차 mvp 도메인과 엔티티 업데이트로 인한 DTO와 mapper 변경사항을 추가하였습니다.
그리고 application, jpa-adaptor, 인수테스트쪽에서 테스트 깨지는 것 모두 수정해놓았습니다

[feat] : 2차 MVP 공용 매퍼, DTO 업데이트

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindAcceptanceTest.java
support/e2e/v1_3_feedback_find.hurl
support/e2e/v2_3_feedback_find.hurl
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/ResponseMapper.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/response/feedback/AbstractFeedbackResponse.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/response/feedback/BookmarkResponse.java

기존 api 인 `질문폼의 모든 피드백 조회`에서 하나의 feedback에서 각각의 문항에 대한 `form_question_feedback_id` 를 추가했습니다.
이젠 해당 id 값으로 `bookmark` 를 달 수 있습니다.
그리고 `bookmark` 필드도 함께 추가했습니다.
그리고 이거 수정하면서 `is_read`도 feedback이 아닌 `form_question_feedback에 대한 is_read`로 변경해놓았습니다 (버그수정)
* 빨간 색은 api 업데이트 되면서 추가한 내용이고,
* 파란 색은 버그 수정한 부분입니다

[refactor] : 질문폼의 모든 피드백 조회 v2로 업데이트, is_read 버그 수정

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/bookmark/BookmarkReplaceAcceptanceTest.java

**질문폼의 북마크된 피드백 교체** API에 대한 인수테스트를 작성했습니다

[feat] : 질문폼의 북마크된 피드백 교체 - `인수테스트` 작성

---

api/api-mock/src/main/java/me/nalab/api/mock/MockController.java

`질문폼의 타입에 해당하는 피드백 조회` 의 mock api에서 formType에 해당하는 키워드를 그에 맞게 수정하였습니다

[fix] : 질문폼의 타입에 해당하는 피드백 조회 mock api 수정

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/BookmarkResponse.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/response/FormQuestionResponseable.java
api/src/main/resources/db/migration/V4__add_bookmark.sql
api/src/main/resources/db/migration/V5__add_target_position.sql
core/data/src/main/java/me/nalab/core/data/feedback/FormFeedbackEntity.java
core/data/src/main/java/me/nalab/core/data/target/TargetEntity.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/dto/BookmarkDto.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/dto/FormQuestionFeedbackDtoable.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/feedback/mapper/FeedbackDtoMapper.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/dto/TargetDto.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/mapper/TargetDtoMapper.java
survey/survey-application/src/test/java/me/nalab/survey/application/RandomFeedbackDtoFixture.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java
survey/survey-domain/src/test/java/me/nalab/survey/domain/AbstractTargetSources.java
survey/survey-domain/src/test/java/me/nalab/survey/domain/feedback/FeedbackDomainTest.java
survey/survey-domain/src/test/java/me/nalab/survey/domain/target/TargetDomainTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/FeedbackEntityMapper.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/TargetEntityMapper.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/RandomFeedbackFixture.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptorTest.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/createfeedback/FeedbackCreateController.java

flyway v6 적용전에, bookmarked_at에 기본값 세팅을 위해, v4, v5 먼저 적용합니다~

[stage] : flyway v4, v5 pre-apply

---

survey/survey-application/src/main/java/module-info.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/repository/FormQuestionFeedbackFindRepository.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/repository/FormQuestionFeedbackUpdateRepository.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/FeedbackEntityMapper.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/bookmark/TestFeedbackSaveJpaRepository.java

질문폼의 북마크된 피드백 교체 API에 대한 jpa-adaptor 부분을 개발 완료했습니다

[feat] : 질문폼의 북마크된 피드백 교체 - `jpa-adaptor` 추가

---

survey/survey-application/src/main/java/me/nalab/survey/application/exception/FormQuestionFeedbackNotExistException.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/authorization/TargetIdFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/authorization/FormQuestionFeedbackIdValidator.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/authorization/FormQuestionFeedbackIdValidatorFactory.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/authorization/FormQuestionFeedbackIdValidatorTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/authorization/repository/TargetIdFindJpaRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptorTest.java

formQuestionFeedbackId로 인증하는 기능을 추가했습니다.

[feat] : `formQuestionFeedbackId`로 Authorization 기능 추가

---

auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
auth/auth-mock/src/main/java/me/nalab/auth/mock/config/MockAuthConfigurer.java
coverage-exclude.luffy
survey/survey-application/src/main/java/me/nalab/survey/application/exception/FormQuestionFeedbackNotExistException.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/authorization/TargetIdFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/authorization/FormQuestionFeedbackIdValidator.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/authorization/FormQuestionFeedbackIdValidatorFactory.java
survey/survey-application/src/main/java/module-info.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/authorization/FormQuestionFeedbackIdValidatorTest.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/Bookmark.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/feedback/FormQuestionFeedbackable.java
survey/survey-domain/src/test/java/me/nalab/survey/domain/feedback/BookmarkTest.java
survey/survey-domain/src/test/java/me/nalab/survey/domain/feedback/FeedbackDomainTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/authorization/repository/TargetIdFindJpaRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/authorization/TargetIdFindAdaptorTest.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/BookmarkReplaceController.java

[feat] : 질문폼의 북마크된 피드백 교체 - `web-adaptor` 구현 완료

---

survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/FormQuestionFeedbackUpdateAdaptor.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/BookmarkReplaceController.java

[fix] : 북마크시 jpa 변경 감지 이용하도록 수정, 인증에 Auth 어노테이션 누락 수정

---

survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/target/update/TargetPositionUpdatePort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/updatetarget/TargetPositionUpdateService.java
survey/survey-application/src/main/java/module-info.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/updatetarget/TargetPositionUpdateServiceTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetPositionUpdateAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/repository/TargetFindRepository.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/repository/TargetPositionUpdateRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetPositionUpdateAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TestTargetFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TestTargetPositionUpdateRepository.java

로그인된 타겟의 정보 수정 API에 대한 `jpa-adaptor` 부분을 개발 완료했습니다

[feat] : 로그인된 타겟의 정보 수정 - `jpa-adaptor` 구현 완료

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/findtarget/TargetFindAcceptanceTest.java

**질문폼에 해당하는 타겟의 정보 조회(인증X)** API에 대한 인수테스트를 작성했습니다

[feat] : 질문폼에 해당하는 타겟의 정보 조회 - `인수테스트` 작성

---

survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findtarget/TargetFindBySurveyIdUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findtarget/TargetFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findtarget/TargetIdFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/findtarget/TargetFindBySurveyIdService.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/findtarget/TargetFindBySurveyIdServiceTest.java

`질문폼에 해당하는 타겟의 정보 조회(인증X)` API에 대한 application 부분을 개발 완료했습니다

[feat] : 질문폼에 해당하는 타겟의 정보 조회 - `application` 추가

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/TargetPositionUpdateAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/request/RequestSample.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/request/TargetPositionUpdateRequest.java
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
coverage-exclude.luffy
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/target/update/TargetPositionUpdateUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/target/update/TargetFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/target/update/TargetPositionUpdatePort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/updatetarget/TargetPositionUpdateService.java
survey/survey-application/src/main/java/module-info.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/updatetarget/TargetPositionUpdateServiceTest.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java
survey/survey-domain/src/test/java/me/nalab/survey/domain/target/TargetDomainTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetPositionUpdateAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/repository/TargetFindRepository.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/updatetarget/repository/TargetPositionUpdateRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TargetPositionUpdateAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TestTargetFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/updatetarget/TestTargetPositionUpdateRepository.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/updatetarget/TargetPositionUpdateController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/updatetarget/request/TargetPositionUpdateRequest.java

`로그인된 타겟의 정보 수정` 기능 개발을 완료했습니다
- closes #317

[feat] : `로그인된 타겟의 정보 수정` 기능 개발 완료

---

survey/survey-application/src/main/java/module-info.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/TargetFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/TargetIdFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/repository/TargetFindJpaRepository.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/repository/TargetIdFindJpaRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TargetFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TargetIdFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TestTargetFindJpaRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findtarget/TestTargetIdFindJpaRepository.java

**질문폼에 해당하는 타겟의 정보 조회(인증X)** API에 대한 `jpa-adaptor` 부분을 개발 완료했습니다

[feat] : 질문폼에 해당하는 타겟의 정보 조회 - `jpa-adaptor` 구현 완료

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java
auth/auth-mock/src/main/java/me/nalab/auth/mock/interceptor/MockAuthInterceptor.java
auth/auth-mock/src/test/java/me/nalab/auth/mock/interceptor/MockAuthInterceptorTest.java
coverage-exclude.luffy
survey/survey-application/src/main/java/module-info.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findtarget/TargetFindBySurveyIdController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findtarget/TargetResponseMapper.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findtarget/response/TargetResponse.java

[feat] : 질문폼에 해당하는 타겟의 정보 조회 - `web-adaptor` 구현 완료

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindByTypeAcceptanceTest.java

**질문폼의 타입에 해당하는 피드백 조회(인증X)** API에 대한 인수테스트를 작성했습니다

[feat] : 질문폼의 타입에 해당하는 피드백 조회 - `인수테스트` 작성

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/AbstractFeedbackTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/FeedbackAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindByTypeAcceptanceTest.java
coverage-exclude.luffy
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/findfeedback/formtype/FeedbackFindByTypeUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/formtype/FeedbackFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/formtype/SurveyFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findfeedback/formtype/TargetIdFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/findfeedback/formtype/FeedbackFindByTypeService.java
survey/survey-application/src/main/java/module-info.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/findfeedback/formtype/FeedbackFindByTypeServiceTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/FeedbackFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/SurveyFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/TargetIdFindAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/repository/FeedbackFindRepository.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/repository/SurveyFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/FeedbackFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/SurveyFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/TargetIdFindAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/TestFeedbackFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/TestSurveyFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/findfeedback/formtype/TestTargetRepository.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/FeedbackFindByFormTypeController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/QuestionFeedbackResponseMapper.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/response/QuestionFeedbackResponse.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/response/formquestion/AbstractFormQuestionResponse.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/response/formquestion/ChoiceFormQuestionResponse.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/response/formquestion/ChoiceResponse.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/response/formquestion/ShortFormQuestionResponse.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/findfeedback/formtype/response/formquestion/ShortResponse.java

**질문폼의 타입에 해당하는 피드백 조회** API에 대한 `jpa-adaptor` 부분을 개발 완료했습니다
**질문폼의 타입에 해당하는 피드백 조회** API에 대한 `web-adaptor` 부분을 개발 완료했습니다

[feat] : 질문폼의 타입에 해당하는 피드백 조회 - `jpa-adaptor` , `web-adaptor` 구현 완료

---

core/secure/src/main/java/me/nalab/core/secure/cors/CorsConfig.java
core/secure/src/main/java/module-info.java

V2 API에서 CORS 에러가 발생하는 에러를 수정했습니다.
- closes #335

[fix] : `/v2 API` CORS 에러 수정

---

coverage-exclude.luffy

coverage-exclude.luffy 개행에 버그가 있어서 수정했습니다.
- closes #340

[fix] : coverage-exclude.luffy 개행 버그 수정

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/exists/SurveyExistsAcceptanceTest.java

jwt를 인자로 받아, survey가 존재하는지 확인하는 인수테스트를 추가했습니다.

[test] : survey 존재 유무 확인 인수테스트 추가

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/exists/SurveyExistsAcceptanceTest.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/existsurvey/SurveyExistUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/existsurvey/SurveyExistPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/existsurvey/SurveyExistService.java
survey/survey-application/src/main/java/module-info.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/existsurvey/SurveyExistServiceTest.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/existsurvey/SurveyExistAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/existsurvey/repository/SurveyFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/SurveyExistAdaptorTest.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/TestSurveyFindRepository.java
survey/survey-jpa-adaptor/src/test/java/me/nalab/survey/jpa/adaptor/existsurvey/TestTargetRepository.java

**survey 존재 유무 확인** API에 대한 `jpa-adaptor` 부분을 개발 완료했습니다

[feat] : survey 존재 유무 확인 - `jpa-adaptor` 구현 완료

---

support/e2e/v1_5_target.hurl

`survey 존재 유무 확인` 새로 추가된 API에 대한 e2e test를 추가하였습니다.
과정은 다음과 같이 진행됩니다.
- 회원가입을 한다
- 발급받은 토큰을 저장한다
- survey를 생성한다
-  ...
기존 v1_5_target 에 해당 api만 추가해서 만들었습니다

[test] : `survey 존재 유무 확인` e2e test 추가

---

.github/workflows/e2e.yml
support/e2e/Dockerfile

HURL 3.0.1 을 사용하고 있었는데, curl중에 SSL 에러가 뜨면서 hurl 다운이 안되네요.
curl로 hurl image 받을때, 인증서 옵션을 꺼놨습니다. 보안 필요한 정보 함께 보내지 않아서, 크게 문제되지 않을거 같아요
_(마침, 3주전 HURL 4.0.0 나왔다고 해서 함께 버전업 PR 날립니다.)_

[chore] : HURL verison 4.0.0으로 업그레이드

---

api/build.gradle
api/src/main/resources/db/migration/V7__add_gallery.sql
build.gradle
gallery/build.gradle
gallery/src/main/kotlin/me/nalab/gallery/domain/Gallery.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/Job.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/Survey.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/Target.kt
gradle.properties
gradle/kotlin.gradle
settings.gradle

Gallery 도메인을 추가했습니다.
조회의 변수가 되는 부분은 역정규화 해놨습니다
``` mermaid
classDiagram
class Gallery {
gallery_id: Long
target: Target
survey: Survey
updateOrder: Instant
}
class Target {
target_id: Long
job: Job
}
class Job {
PM
DEVELOPER
DESIGNER
}
class Survey {
survey_id: Long
bookmarkedCount: Int
}
class TimeBaseEntity {
createdAt: Instant
updatedAt: Instant
}
Gallery --|> TimeBaseEntity
Gallery --> Target
Gallery --> Survey
Target --> Job
```
(타겟의 position, Survey의 저장횟수)
- close #368

[feat] : gallery 도메인 추가

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/TargetInitializer.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/AbstractSurveyTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/bookmark/SurveyBookmarkAcceptanceTest.java
api/src/main/resources/db/migration/V8__add_job_bookmark_img_to_target.sql
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
auth/auth-mock/src/main/java/me/nalab/auth/mock/config/MockAuthConfigurer.java
core/data/src/main/java/me/nalab/core/data/target/SurveyBookmarkEntity.java
core/data/src/main/java/me/nalab/core/data/target/TargetEntity.java
support/e2e/v1_7_bookmark_survey.hurl
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/dto/SurveyBookmarkDto.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/bookmark/SurveyBookmarkReplaceUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findtarget/TargetFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/SurveyBookmarkReplaceService.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/SurveyBookmark.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/TargetEntityMapper.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/TargetFindAdaptor.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/SurveyBookmarkReplaceController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/response/SurveyBookmarkResponse.java

survey에 북마크하는기능을 추가했습니다.
- close #363

[feat]: Bookmark to survey

---

core/data/src/main/java/me/nalab/core/data/target/SurveyBookmarkEntity.java
core/data/src/main/java/me/nalab/core/data/target/TargetEntity.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/bookmark/SurveyBookmarkUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/bookmark/SurveyBookmarkPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/SurveyBookmarkService.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/SurveyBookmarkAdaptor.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/TargetEntityMapper.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/SurveyBookmarkReplaceController.java

Survey에 북마크를 해도 변경감지가 동작하지 않아서, 반영되지 않는 버그를 수정했습니다.
- close #377

[fix] : SurveyBookmark 변경감지가 동작하지 않는 버그 수정

---

api/acceptance-test/build.gradle
api/src/main/java/me/nalab/api/NalabApplication.java
api/src/main/resources/db/migration/V9__gallery_target_id_idx.sql
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
gallery/build.gradle
gallery/src/main/kotlin/me/nalab/gallery/app/GalleryPreviewDtoMapper.kt
gallery/src/main/kotlin/me/nalab/gallery/app/GalleryRegisterApp.kt
gallery/src/main/kotlin/me/nalab/gallery/controller/GalleryController.kt
gallery/src/main/kotlin/me/nalab/gallery/controller/request/GalleryRegisterRequest.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/Gallery.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryRepository.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryService.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/response/GalleryDto.kt
gallery/src/main/kotlin/me/nalab/gallery/infra/SurveyBookmarkedListener.kt
gallery/src/test/kotlin/me/nalab/gallery/domain/GalleryFixture.kt
gallery/src/test/kotlin/me/nalab/gallery/domain/GalleryServiceTest.kt
support/e2e/v1_9_register_gallery.hurl
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/dto/TargetDto.java
survey/survey-application/src/main/java/me/nalab/survey/application/common/survey/mapper/TargetDtoMapper.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/bookmark/SurveyBookmarkListenPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/SurveyBookmarkService.java

내 Gallery 등록 기능을 추가했습니다.
- close #361

[feat] : 내 Gallery 등록 기능 추가

---

auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
gallery/src/main/kotlin/me/nalab/gallery/app/GalleryGetApp.kt
gallery/src/main/kotlin/me/nalab/gallery/controller/GalleryController.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryService.kt
support/e2e/v1_10_get_logined_gallery.hurl

로그인한 유저의 gallery 조회기능을 추가했습니다.
- close #360

[feat]: 로그인한 유저의 gallery조회 기능 추가

---

api/src/main/resources/db/migration/v10_gallery_covering_idx.sql
api/src/main/resources/db/migration/v10_gallery_update_bookmark_idx.sql
gallery/src/main/kotlin/me/nalab/gallery/app/GalleryGetApp.kt
gallery/src/main/kotlin/me/nalab/gallery/controller/GalleryController.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryRepository.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryService.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/response/GalleriesDto.kt
gallery/src/test/kotlin/me/nalab/gallery/app/SurveyFixture.kt
gallery/src/test/kotlin/me/nalab/gallery/domain/GalleryFixture.kt
gallery/src/test/kotlin/me/nalab/gallery/domain/GalleryServiceTest.kt

전체 Gallery 조회 기능을 추가했습니다.
- 조회 성능 향상용으로 커버링인덱스 부착 or 안부착? (지금은 부착)
- update, bookmark는 카디널리티가 낮고 변경이 잦은데 index 부착이 맞는 선택인가? (지금은 정렬 + 커버링 인덱스 태우기용으로 index부착)
- Pagination 보다 좋은 방법이 있을지?
무한스크롤 쿼리 구현할때, 마지막 gallery id 찍고 다음꺼부터 내려주는식으로 하려고 했는데, 지금 update, bookmark 정렬 필터가 추가로 들어가면서 이 방식으로 구현이 힘듬 (update, bookmark로 정렬하는순간 마지막 gallery id가 필요 없기때문)
그래서 Pagination 방식으로 구현했음. 
- close #362

[feat] : 전체 Gallery 조회 기능 추가

---

.github/workflows/docker-release-publisher.yml

docker image가 push 되지 않는 버그 수정 hotfix 입니다.

[fix] : docker image push 되지 않는 버그 수정

---

api/src/main/resources/db/migration/v11_survey_unique_index_target.sql
core/data/src/main/java/me/nalab/core/data/survey/SurveyEntity.java
support/e2e/v1_2_feedback_create.hurl
support/e2e/v1_3_feedback_find.hurl
support/e2e/v1_4_bookmark.hurl
support/e2e/v1_6_find_gallery_preview.hurl
support/e2e/v1_7_bookmark_survey.hurl
support/e2e/v2_3_feedback_find.hurl
survey/survey-application/src/main/java/me/nalab/survey/application/exception/DuplicateSurveyException.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/create/SurveyCreateService.java
survey/survey-application/src/test/java/me/nalab/survey/application/service/create/SurveyCreateServiceTest.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/advice/SurveyControllerAdvice.java

Survey가 여러개 있을때, 최신 Survey를 반환하도록 수정

[release]: 중복 survey생성을 막는다

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/SurveyAcceptanceValidator.java
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
gallery/src/main/kotlin/me/nalab/gallery/app/GalleryGetApp.kt
gallery/src/main/kotlin/me/nalab/gallery/controller/GalleryController.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/Gallery.kt
gallery/src/main/kotlin/me/nalab/gallery/domain/GalleryService.kt
gallery/src/main/kotlin/me/nalab/gallery/infra/SurveyBookmarkedListener.kt
support/e2e/v1_10_get_logined_gallery.hurl
support/e2e/v1_11_cancel_bookmark_survey.hurl
support/e2e/v1_7_bookmark_survey.hurl
support/e2e/v1_9_register_gallery.hurl
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/bookmark/SurveyBookmarkUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/bookmark/SurveyBookmarkListenPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/bookmark/SurveyBookmarkPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/SurveyBookmarkService.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/bookmark/SurveyBookmarkAdaptor.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/SurveyBookmarkController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/SurveyBookmarkReplaceController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/response/SurveyBookmarkedResponse.java

survey에 북마크 취소기능을 개발했습니다.
- close #387

[feat]: survey에 북마크 취소기능 개발

---

auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
support/e2e/v1_12_find_bookmarked_survey.hurl
survey/survey-application/src/main/java/me/nalab/survey/application/port/in/web/bookmark/BookmarkedSurveyFindUseCase.java
survey/survey-application/src/main/java/me/nalab/survey/application/port/out/persistence/findtarget/TargetFindPort.java
survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/BookmarkedSurveyFindService.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/common/mapper/TargetEntityMapper.java
survey/survey-jpa-adaptor/src/main/java/me/nalab/survey/jpa/adaptor/findtarget/TargetFindAdaptor.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/BookmarkedSurveyFindController.java
survey/survey-web-adaptor/src/main/java/me/nalab/survey/web/adaptor/bookmark/response/SurveyBookmarksResponse.java

로그인한 유저가 북마크한 survey들을 조회하는 기능 추가
- close #389

[feat] : 로그인한 유저가 북마크한 survey 조회 기능을 추가한다

---

core/data/src/main/java/me/nalab/core/data/target/TargetEntity.java
gallery/src/test/kotlin/me/nalab/gallery/domain/GalleryServiceTest.kt
survey/survey-application/src/main/java/me/nalab/survey/application/service/bookmark/SurveyBookmarkService.java
survey/survey-domain/src/main/java/me/nalab/survey/domain/target/Target.java

북마크를 누른 대상의 북마크된 카운트 가 증가하는 버그를 수정했습니다.

[fix] : bookmark 카운트가 bookmark한 대상에게 증가하는 버그 수정

---

auth/auth-application/src/main/java/me/nalab/auth/application/common/exception/AuthException.java
auth/auth-application/src/main/java/me/nalab/auth/application/common/utils/JwtUtils.java
auth/auth-application/src/main/java/module-info.java
auth/auth-web-adaptor/build.gradle
auth/auth-web-adaptor/src/main/java/me/nalab/auth/web/adaptor/advice/AuthControllerAdvice.java
auth/auth-web-adaptor/src/main/java/module-info.java
core/exception-handler/src/main/java/module-info.java

Jwt decrypt 예외시 500 에러가 발생하고 있어서, 핸들링 로직을 추가했습니다.
- close #402

fix: JWT decrypt 예외시 AuthException을 던지도록하고, 전역 Advice를 등록

---

api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/bookmark/BookmarkReplaceAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/create/FeedbackCreateAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/find/FeedbackFindByTypeAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findreviewers/ReviewersFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findspecific/SpecificFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/findsummary/FeedbackFindSummaryAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/feedback/reviewer/summary/ReviewerSummarizeAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/bookmark/SurveyBookmarkAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/create/SurveyCreateAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/exists/SurveyExistsAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/find/SurveyFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/findid/SurveyFindidAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/survey/findtarget/TargetFindAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/UserAcceptanceTestSupporter.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/delete/UserDeleteAcceptanceTest.java
api/acceptance-test/src/test/java/me/nalab/luffy/api/acceptance/test/user/updatetarget/TargetPositionUpdateAcceptanceTest.java
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/AuthenticateHeaderPrefix.java
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptor.java
auth/auth-mock/src/main/java/me/nalab/auth/mock/interceptor/AuthenticateHeaderPrefix.java
auth/auth-mock/src/main/java/me/nalab/auth/mock/interceptor/MockAuthInterceptor.java
auth/auth-mock/src/test/java/me/nalab/auth/mock/interceptor/MockAuthInterceptorTest.java
user/user-application/src/main/java/me/nalab/user/application/port/in/UserDeleteUseCase.java
user/user-application/src/main/java/me/nalab/user/application/port/out/persistence/UserDeletePort.java
user/user-application/src/main/java/me/nalab/user/application/service/UserDeleteService.java
user/user-jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/UserDeleteAdaptor.java
user/user-jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/UserGetAdaptor.java
user/user-jpa-adapter/src/main/java/me/nalab/user/jpa/adaptor/create/repository/UserOAuthInfoJpaRepository.java
user/user-web-adaptor/src/main/java/me/nalab/user/web/adaptor/logined/DeleteUserController.java

token을 받아서 유저를 삭제하는 API를 개발했습니다.
- (유저 삭제되면 다음 로그인 email, provider 를 받을때 새로운 유저로 가입되어서 중복조회 발생 x)
- (target 찾을때, 위 이유 때문에 삭제되면 같은 타겟 안나옴)
- close #404

feat: User 삭제 API 개발

---

auth/auth-application/src/test/java/me/nalab/auth/application/service/JwtLoginedDecryptServiceTest.java
auth/auth-interceptor/src/main/java/me/nalab/auth/interceptor/JwtDecryptInterceptorConfigurer.java
auth/auth-mock/src/main/java/me/nalab/auth/mock/config/MockAuthConfigurer.java
user/user-application/src/main/java/me/nalab/user/application/common/dto/TokenInfo.java
user/user-application/src/main/java/me/nalab/user/application/service/LoginedUserGetByTokenService.java
user/user-application/src/main/java/me/nalab/user/application/service/UserDeleteService.java
user/user-application/src/test/java/me/nalab/user/application/service/LoginedUserGetByTokenServiceTest.java
user/user-web-adaptor/src/main/java/me/nalab/user/web/adaptor/logined/LoginedUserGetController.java

https://github.com/depromeet/na-lab-server/pull/406
이거 리뷰 수정 내용입니다
PR이 main -> release라 열려있는 PR때문에 main에 push하면 바로 배포되서 branch따로 만들었어요

refactor: TokenInfo를 record로 변경하고 token-value 부분을 받도록 수정한다
